import { ModelConfig } from './ai-routing';

export const EXPANDED_MODELS: ModelConfig[] = [
  // OpenAI Models (Updated)
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    modelId: 'gpt-4-turbo-preview',
    costPer1kInput: 0.01,
    costPer1kOutput: 0.03,
    maxTokens: 128000,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: true,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: true,
    isOpenSource: false,
    requiresGPU: false,
    strengths: ['complex reasoning', 'code generation', 'analysis', 'mathematics', 'creative writing'],
    weaknesses: ['cost', 'speed'],
    bestFor: ['complex problem solving', 'advanced coding', 'detailed analysis'],
    apiUrl: 'https://api.openai.com/v1/chat/completions',
    contextWindow: 128000,
    trainingData: 'Up to April 2024',
    releaseDate: '2024-04-09',
    license: 'Proprietary',
    architecture: 'Transformer',
    languages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'zh']
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    modelId: 'gpt-4o',
    costPer1kInput: 0.005,
    costPer1kOutput: 0.015,
    maxTokens: 128000,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: true,
    isOpenSource: false,
    requiresGPU: false,
    strengths: ['multimodal', 'fast', 'cost-effective', 'reasoning'],
    weaknesses: ['newer model', 'less tested'],
    bestFor: ['general purpose', 'multimodal tasks', 'real-time applications'],
    apiUrl: 'https://api.openai.com/v1/chat/completions',
    contextWindow: 128000,
    trainingData: 'Up to October 2023',
    releaseDate: '2024-05-13',
    license: 'Proprietary',
    architecture: 'Transformer',
    languages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'zh']
  },

  // Meta/Llama Models
  {
    id: 'llama-3-70b',
    name: 'Llama 3 70B',
    provider: 'meta',
    modelId: 'meta-llama/Llama-3-70b-chat-hf',
    costPer1kInput: 0.0009,
    costPer1kOutput: 0.0009,
    maxTokens: 8192,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['open source', 'reasoning', 'multilingual', 'code generation'],
    weaknesses: ['requires GPU', 'limited context'],
    bestFor: ['open source projects', 'custom fine-tuning', 'cost-effective reasoning'],
    apiUrl: 'https://api.together.xyz/inference',
    contextWindow: 8192,
    trainingData: 'Up to March 2024',
    releaseDate: '2024-04-18',
    license: 'Custom (Llama 3)',
    modelSize: '70B parameters',
    architecture: 'Llama',
    languages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'hi', 'th']
  },
  {
    id: 'llama-3-8b',
    name: 'Llama 3 8B',
    provider: 'meta',
    modelId: 'meta-llama/Llama-3-8b-chat-hf',
    costPer1kInput: 0.0002,
    costPer1kOutput: 0.0002,
    maxTokens: 8192,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['fast', 'efficient', 'open source', 'good reasoning'],
    weaknesses: ['smaller model', 'limited capabilities'],
    bestFor: ['fast inference', 'edge deployment', 'cost-sensitive applications'],
    apiUrl: 'https://api.together.xyz/inference',
    contextWindow: 8192,
    trainingData: 'Up to March 2024',
    releaseDate: '2024-04-18',
    license: 'Custom (Llama 3)',
    modelSize: '8B parameters',
    architecture: 'Llama',
    languages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'hi', 'th']
  },

  // Hugging Face Models
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'huggingface',
    modelId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    costPer1kInput: 0.0007,
    costPer1kOutput: 0.0007,
    maxTokens: 32768,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['mixture of experts', 'efficient', 'multilingual', 'open source'],
    weaknesses: ['requires GPU', 'complex architecture'],
    bestFor: ['multilingual tasks', 'efficient inference', 'code generation'],
    apiUrl: 'https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1',
    contextWindow: 32768,
    trainingData: 'Up to 2024',
    releaseDate: '2024-01-08',
    license: 'Apache 2.0',
    modelSize: '8x7B parameters (MoE)',
    architecture: 'Mixtral (Mixture of Experts)',
    languages: ['en', 'fr', 'es', 'de', 'it', 'pt', 'ru', 'zh', 'ja']
  },
  {
    id: 'codellama-34b',
    name: 'Code Llama 34B',
    provider: 'huggingface',
    modelId: 'codellama/CodeLlama-34b-Instruct-hf',
    costPer1kInput: 0.0008,
    costPer1kOutput: 0.0008,
    maxTokens: 16384,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: true,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['code generation', 'code completion', 'debugging', 'multiple languages'],
    weaknesses: ['code-focused only', 'requires GPU'],
    bestFor: ['code generation', 'programming assistance', 'code review'],
    apiUrl: 'https://api-inference.huggingface.co/models/codellama/CodeLlama-34b-Instruct-hf',
    contextWindow: 16384,
    trainingData: 'Code datasets up to 2023',
    releaseDate: '2023-08-24',
    license: 'Custom (Llama 2)',
    modelSize: '34B parameters',
    architecture: 'Llama',
    languages: ['python', 'javascript', 'java', 'c++', 'c', 'php', 'typescript', 'go', 'rust', 'swift']
  },

  // Chinese Models
  {
    id: 'qwen-72b',
    name: 'Qwen 72B',
    provider: 'alibaba',
    modelId: 'qwen/Qwen-72B-Chat',
    costPer1kInput: 0.002,
    costPer1kOutput: 0.002,
    maxTokens: 32768,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['Chinese language', 'multilingual', 'reasoning', 'math'],
    weaknesses: ['requires GPU', 'Chinese-focused'],
    bestFor: ['Chinese language tasks', 'multilingual applications', 'Asian markets'],
    apiUrl: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation',
    contextWindow: 32768,
    trainingData: 'Multilingual data up to 2023',
    releaseDate: '2023-08-03',
    license: 'Custom (Tongyi Qianwen)',
    modelSize: '72B parameters',
    architecture: 'Transformer',
    languages: ['zh', 'en', 'ja', 'ko', 'vi', 'th', 'ms', 'id'],
    region: 'China'
  },
  {
    id: 'baichuan-13b',
    name: 'Baichuan 13B',
    provider: 'baichuan',
    modelId: 'baichuan-inc/Baichuan-13B-Chat',
    costPer1kInput: 0.001,
    costPer1kOutput: 0.001,
    maxTokens: 4096,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['Chinese language', 'efficient', 'open source'],
    weaknesses: ['limited context', 'Chinese-focused'],
    bestFor: ['Chinese language tasks', 'efficient inference', 'chatbots'],
    apiUrl: 'https://api.baichuan-ai.com/v1/chat/completions',
    contextWindow: 4096,
    trainingData: 'Chinese and English data up to 2023',
    releaseDate: '2023-07-11',
    license: 'Apache 2.0',
    modelSize: '13B parameters',
    architecture: 'Transformer',
    languages: ['zh', 'en'],
    region: 'China'
  },

  // Japanese Models
  {
    id: 'rinna-japanese-gpt',
    name: 'Rinna Japanese GPT',
    provider: 'huggingface',
    modelId: 'rinna/japanese-gpt-neox-3.6b-instruction-sft',
    costPer1kInput: 0.0005,
    costPer1kOutput: 0.0005,
    maxTokens: 2048,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: false,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['Japanese language', 'cultural context', 'efficient'],
    weaknesses: ['Japanese only', 'smaller model'],
    bestFor: ['Japanese language tasks', 'cultural content', 'Japan market'],
    apiUrl: 'https://api-inference.huggingface.co/models/rinna/japanese-gpt-neox-3.6b-instruction-sft',
    contextWindow: 2048,
    trainingData: 'Japanese web data up to 2023',
    releaseDate: '2023-03-15',
    license: 'MIT',
    modelSize: '3.6B parameters',
    architecture: 'GPT-NeoX',
    languages: ['ja'],
    region: 'Japan'
  },

  // European Models
  {
    id: 'bloom-176b',
    name: 'BLOOM 176B',
    provider: 'huggingface',
    modelId: 'bigscience/bloom',
    costPer1kInput: 0.002,
    costPer1kOutput: 0.002,
    maxTokens: 2048,
    supportsStreaming: false,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: true,
    strengths: ['multilingual', 'open source', 'large model', 'European focus'],
    weaknesses: ['slow inference', 'requires significant GPU'],
    bestFor: ['multilingual tasks', 'research', 'European languages'],
    apiUrl: 'https://api-inference.huggingface.co/models/bigscience/bloom',
    contextWindow: 2048,
    trainingData: 'Multilingual data up to 2022',
    releaseDate: '2022-07-06',
    license: 'BigScience OpenRAIL-M',
    modelSize: '176B parameters',
    architecture: 'Transformer',
    languages: ['fr', 'es', 'en', 'de', 'pt', 'ar', 'zh', 'hi', 'id', 'vi'],
    region: 'Europe'
  },

  // Russian Models
  {
    id: 'rugpt-large',
    name: 'ruGPT-3.5 Large',
    provider: 'huggingface',
    modelId: 'ai-forever/rugpt3large_based_on_gpt2',
    costPer1kInput: 0.0008,
    costPer1kOutput: 0.0008,
    maxTokens: 2048,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: false,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['Russian language', 'cultural context', 'open source'],
    weaknesses: ['Russian only', 'limited context'],
    bestFor: ['Russian language tasks', 'cultural content', 'Russian market'],
    apiUrl: 'https://api-inference.huggingface.co/models/ai-forever/rugpt3large_based_on_gpt2',
    contextWindow: 2048,
    trainingData: 'Russian web data up to 2021',
    releaseDate: '2021-05-20',
    license: 'MIT',
    modelSize: '760M parameters',
    architecture: 'GPT-2',
    languages: ['ru'],
    region: 'Russia'
  },

  // Specialized Models
  {
    id: 'stable-code-3b',
    name: 'Stable Code 3B',
    provider: 'stability',
    modelId: 'stabilityai/stable-code-3b',
    costPer1kInput: 0.0003,
    costPer1kOutput: 0.0003,
    maxTokens: 16384,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: true,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['code generation', 'fast inference', 'efficient', 'multiple languages'],
    weaknesses: ['code-focused only', 'smaller model'],
    bestFor: ['code completion', 'programming assistance', 'IDE integration'],
    apiUrl: 'https://api-inference.huggingface.co/models/stabilityai/stable-code-3b',
    contextWindow: 16384,
    trainingData: 'Code datasets up to 2023',
    releaseDate: '2024-01-16',
    license: 'Stability AI Non-Commercial',
    modelSize: '3B parameters',
    architecture: 'Transformer',
    languages: ['python', 'javascript', 'java', 'c++', 'c', 'go', 'rust', 'typescript']
  },

  // Video Generation Models
  {
    id: 'runway-gen2',
    name: 'Runway Gen-2',
    provider: 'runpod',
    modelId: 'runwayml/gen-2',
    costPer1kInput: 0.1,
    costPer1kOutput: 0,
    maxTokens: 1000,
    supportsStreaming: false,
    supportsImages: true,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: true,
    supportsCode: false,
    supportsFunction: false,
    isOpenSource: false,
    requiresGPU: true,
    strengths: ['video generation', 'high quality', 'text-to-video'],
    weaknesses: ['expensive', 'slow', 'limited availability'],
    bestFor: ['video content creation', 'marketing materials', 'creative projects'],
    apiUrl: 'https://api.runwayml.com/v1/generate',
    contextWindow: 1000,
    trainingData: 'Video datasets up to 2023',
    releaseDate: '2023-06-26',
    license: 'Proprietary',
    architecture: 'Diffusion',
    languages: ['en']
  },

  // Local/Ollama Models
  {
    id: 'llama2-7b-local',
    name: 'Llama 2 7B (Local)',
    provider: 'ollama',
    modelId: 'llama2:7b',
    costPer1kInput: 0,
    costPer1kOutput: 0,
    maxTokens: 4096,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['local deployment', 'privacy', 'no API costs', 'offline'],
    weaknesses: ['requires local setup', 'limited by hardware'],
    bestFor: ['privacy-sensitive tasks', 'offline use', 'development'],
    apiUrl: 'http://localhost:11434/api/generate',
    contextWindow: 4096,
    trainingData: 'Up to September 2022',
    releaseDate: '2023-07-18',
    license: 'Custom (Llama 2)',
    modelSize: '7B parameters',
    architecture: 'Llama',
    languages: ['en']
  },

  // Custom/User Models Placeholder
  {
    id: 'custom-model-template',
    name: 'Custom Model Template',
    provider: 'custom',
    modelId: 'user/custom-model',
    costPer1kInput: 0,
    costPer1kOutput: 0,
    maxTokens: 4096,
    supportsStreaming: true,
    supportsImages: false,
    supportsVision: false,
    supportsAudio: false,
    supportsVideo: false,
    supportsCode: true,
    supportsFunction: false,
    isOpenSource: true,
    requiresGPU: false,
    strengths: ['customizable', 'user-defined', 'specific use case'],
    weaknesses: ['requires setup', 'user maintenance'],
    bestFor: ['specialized tasks', 'custom domains', 'proprietary data'],
    apiUrl: 'https://user-defined-endpoint.com/api',
    contextWindow: 4096,
    trainingData: 'User-defined',
    releaseDate: 'User-defined',
    license: 'User-defined',
    modelSize: 'User-defined',
    architecture: 'User-defined',
    languages: ['user-defined']
  }
];

// Model categories for easy filtering
export const MODEL_CATEGORIES = {
  TEXT_GENERATION: ['gpt-4-turbo', 'gpt-4o', 'claude-3-opus', 'claude-3-sonnet', 'llama-3-70b', 'mixtral-8x7b'],
  CODE_GENERATION: ['gpt-4-turbo', 'codellama-34b', 'stable-code-3b', 'claude-3-opus'],
  IMAGE_GENERATION: ['dalle-3', 'stable-diffusion-xl', 'midjourney-v6'],
  VIDEO_GENERATION: ['runway-gen2'],
  MULTILINGUAL: ['gpt-4o', 'claude-3-sonnet', 'gemini-pro', 'qwen-72b', 'bloom-176b'],
  OPEN_SOURCE: ['llama-3-70b', 'llama-3-8b', 'mixtral-8x7b', 'codellama-34b', 'stable-code-3b'],
  LOCAL_DEPLOYMENT: ['llama2-7b-local', 'ollama'],
  CHINESE: ['qwen-72b', 'baichuan-13b'],
  JAPANESE: ['rinna-japanese-gpt'],
  RUSSIAN: ['rugpt-large'],
  FAST_INFERENCE: ['llama-3-8b', 'claude-3-haiku', 'gpt-3.5-turbo', 'stable-code-3b'],
  LOW_COST: ['llama-3-8b', 'claude-3-haiku', 'gpt-3.5-turbo', 'stable-code-3b'],
  HIGH_QUALITY: ['gpt-4-turbo', 'claude-3-opus', 'gpt-4o', 'llama-3-70b']
};

// Provider information
export const PROVIDER_INFO = {
  openai: { name: 'OpenAI', website: 'https://openai.com', requiresKey: true },
  anthropic: { name: 'Anthropic', website: 'https://anthropic.com', requiresKey: true },
  google: { name: 'Google', website: 'https://ai.google.dev', requiresKey: true },
  huggingface: { name: 'Hugging Face', website: 'https://huggingface.co', requiresKey: true },
  meta: { name: 'Meta', website: 'https://ai.meta.com', requiresKey: false },
  alibaba: { name: 'Alibaba Cloud', website: 'https://www.alibabacloud.com', requiresKey: true },
  baichuan: { name: 'Baichuan AI', website: 'https://www.baichuan-ai.com', requiresKey: true },
  stability: { name: 'Stability AI', website: 'https://stability.ai', requiresKey: true },
  runpod: { name: 'RunPod', website: 'https://runpod.io', requiresKey: true },
  ollama: { name: 'Ollama', website: 'https://ollama.ai', requiresKey: false },
  custom: { name: 'Custom Provider', website: '', requiresKey: true }
};