import { z } from 'zod';

// Core model configuration schema
export const ModelSchema = z.object({
  id: z.string(),
  name: z.string(),
  provider: z.enum([
    // Major LLM providers
    'openai', 'anthropic', 'google', 'cohere', 'mistral', 'meta',
    'huggingface', 'ollama', 'together', 'perplexity', 'groq',
    'replicate', 'stability', 'midjourney', 'runpod',
    // New LLM providers (2024)
    'deepseek', 'xai', 'fireworks', 'openrouter', 'anyscale', 'nvidia', 'qwen',
    // Specialized audio/media providers
    'elevenlabs', 'assemblyai', 'deepgram', 'suno', 'runway'
  ]),
  modelId: z.string(),
  apiUrl: z.string().optional(),
  apiKey: z.string().optional(),
  costPer1kTokens: z.number().default(0),
  maxTokens: z.number().default(4096),
  contextWindow: z.number().default(4096),
  supportsChat: z.boolean().default(true),
  supportsCode: z.boolean().default(true),
  supportsVision: z.boolean().default(false),
  supportsFiles: z.boolean().default(false),
  supportsStreaming: z.boolean().default(false),
  modelSize: z.string().optional(),
  description: z.string().optional(),
  strengths: z.array(z.string()).default([]),
  languages: z.array(z.string()).default(['en']),
  enabled: z.boolean().default(true),
  priority: z.number().default(50),
  category: z.enum([
    'CHAT', 'CODE', 'REASONING', 'CREATIVE', 'FAST', 'VISION', 'MULTIMODAL',
    'IMAGE_GEN', 'VIDEO_GEN', 'AUDIO_STT', 'AUDIO_TTS', 'EMBEDDING'
  ]).default('CHAT'),
  tier: z.enum(['FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE']).default('FREE'),
  // New capability flags
  supportsImageGen: z.boolean().default(false),
  supportsAudioInput: z.boolean().default(false),
  supportsAudioOutput: z.boolean().default(false),
  supportsEmbeddings: z.boolean().default(false)
});

export type Model = z.infer<typeof ModelSchema>;

// Raw model configurations that will be validated and filled with defaults
const RAW_MODELS = [
  // ===== OPEN SOURCE MODELS (FREE) =====

  // Meta Llama Models (HuggingFace)
  {
    id: 'llama-2-7b-chat',
    name: 'Llama 2 7B Chat',
    provider: 'huggingface',
    modelId: 'meta-llama/Llama-2-7b-chat-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: true,
    supportsCode: true,
    modelSize: '7B',
    description: 'Meta\'s Llama 2 model optimized for conversations',
    strengths: ['conversational', 'general-purpose', 'fast'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 10
  },
  {
    id: 'llama-2-13b-chat',
    name: 'Llama 2 13B Chat',
    provider: 'huggingface',
    modelId: 'meta-llama/Llama-2-13b-chat-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/meta-llama/Llama-2-13b-chat-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: true,
    supportsCode: true,
    modelSize: '13B',
    description: 'Larger Llama 2 model for complex reasoning',
    strengths: ['reasoning', 'detailed-analysis', 'quality'],
    category: 'REASONING',
    tier: 'FREE',
    priority: 15
  },

  // Code Llama Models
  {
    id: 'code-llama-7b',
    name: 'Code Llama 7B',
    provider: 'huggingface',
    modelId: 'codellama/CodeLlama-7b-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/codellama/CodeLlama-7b-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: true,
    modelSize: '7B',
    description: 'Meta\'s Code Llama for code generation',
    strengths: ['code-generation', 'programming', 'debugging'],
    category: 'CODE',
    tier: 'FREE',
    priority: 5
  },
  {
    id: 'code-llama-13b',
    name: 'Code Llama 13B',
    provider: 'huggingface',
    modelId: 'codellama/CodeLlama-13b-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/codellama/CodeLlama-13b-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: true,
    modelSize: '13B',
    description: 'Larger Code Llama for complex programming tasks',
    strengths: ['complex-code', 'architecture', 'algorithms'],
    category: 'CODE',
    tier: 'FREE',
    priority: 8
  },

  // Mistral Models
  {
    id: 'mistral-7b-instruct',
    name: 'Mistral 7B Instruct',
    provider: 'huggingface',
    modelId: 'mistralai/Mistral-7B-Instruct-v0.1',
    apiUrl: 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    modelSize: '7B',
    description: 'Mistral\'s efficient instruct model',
    strengths: ['multilingual', 'efficient', 'instruction-following'],
    languages: ['en', 'fr', 'de', 'es', 'it'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 12
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'huggingface',
    modelId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    apiUrl: 'https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1',
    costPer1kTokens: 0,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    modelSize: '8x7B',
    description: 'Mistral\'s mixture of experts model',
    strengths: ['high-quality', 'multilingual', 'reasoning'],
    languages: ['en', 'fr', 'de', 'es', 'it'],
    category: 'REASONING',
    tier: 'FREE',
    priority: 18
  },

  // Other Open Source Models
  {
    id: 'starcoder',
    name: 'StarCoder',
    provider: 'huggingface',
    modelId: 'bigcode/starcoder',
    apiUrl: 'https://api-inference.huggingface.co/models/bigcode/starcoder',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: true,
    modelSize: '15.5B',
    description: 'BigCode\'s advanced code generation model',
    strengths: ['code-completion', 'multiple-languages', 'advanced-programming'],
    category: 'CODE',
    tier: 'FREE',
    priority: 20
  },
  {
    id: 'flan-t5-xl',
    name: 'Flan-T5 XL',
    provider: 'huggingface',
    modelId: 'google/flan-t5-xl',
    apiUrl: 'https://api-inference.huggingface.co/models/google/flan-t5-xl',
    costPer1kTokens: 0,
    maxTokens: 512,
    contextWindow: 512,
    supportsChat: true,
    supportsCode: false,
    modelSize: '3B',
    description: 'Google\'s instruction-tuned T5 model',
    strengths: ['question-answering', 'instructions', 'factual'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 25
  },
  {
    id: 'phi-2',
    name: 'Microsoft Phi-2',
    provider: 'huggingface',
    modelId: 'microsoft/phi-2',
    apiUrl: 'https://api-inference.huggingface.co/models/microsoft/phi-2',
    costPer1kTokens: 0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: true,
    supportsCode: true,
    modelSize: '2.7B',
    description: 'Microsoft\'s small but capable model',
    strengths: ['fast', 'efficient', 'general-purpose'],
    category: 'FAST',
    tier: 'FREE',
    priority: 6
  },
  {
    id: 'gpt2',
    name: 'GPT-2',
    provider: 'huggingface',
    modelId: 'gpt2',
    apiUrl: 'https://api-inference.huggingface.co/models/gpt2',
    costPer1kTokens: 0,
    maxTokens: 1024,
    contextWindow: 1024,
    supportsChat: true,
    supportsCode: false,
    modelSize: '124M',
    description: 'OpenAI\'s GPT-2 (reliable fallback)',
    strengths: ['reliable', 'fast', 'always-available'],
    category: 'FAST',
    tier: 'FREE',
    priority: 100 // Fallback model
  },

  // ===== PAID MODELS =====

  // OpenAI Models
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    modelId: 'gpt-4o',
    costPer1kTokens: 5.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    supportsStreaming: true,
    description: 'OpenAI\'s most advanced multimodal model',
    strengths: ['multimodal', 'reasoning', 'vision', 'highest-quality'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    modelId: 'gpt-4o-mini',
    costPer1kTokens: 0.15,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenAI\'s efficient and affordable model',
    strengths: ['cost-effective', 'fast', 'multimodal'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 3
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    modelId: 'gpt-3.5-turbo',
    costPer1kTokens: 0.5,
    maxTokens: 4096,
    contextWindow: 16385,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'OpenAI\'s fast and affordable model',
    strengths: ['fast', 'affordable', 'reliable'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 7
  },

  // Anthropic Models
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    costPer1kTokens: 3.0,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic\'s most advanced model',
    strengths: ['reasoning', 'analysis', 'safety', 'long-context'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'anthropic',
    modelId: 'claude-3-haiku-20240307',
    costPer1kTokens: 0.25,
    maxTokens: 4096,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Anthropic\'s fast and efficient model',
    strengths: ['fast', 'efficient', 'cost-effective'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 4
  },

  // Google Models
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    modelId: 'gemini-1.5-pro',
    costPer1kTokens: 7.0,
    maxTokens: 8192,
    contextWindow: 2000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Google\'s advanced multimodal model',
    strengths: ['multimodal', 'very-long-context', 'reasoning'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    modelId: 'gemini-1.5-flash',
    costPer1kTokens: 0.075,
    maxTokens: 8192,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Google\'s fast multimodal model',
    strengths: ['fast', 'multimodal', 'long-context'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 11
  },

  // Groq Models (Fast Inference)
  {
    id: 'groq-llama-3-70b',
    name: 'Llama 3 70B (Groq)',
    provider: 'groq',
    modelId: 'llama3-70b-8192',
    costPer1kTokens: 0.59,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    description: 'Meta\'s Llama 3 on Groq\'s fast inference',
    strengths: ['very-fast', 'high-quality', 'reasoning'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 13
  },
  {
    id: 'groq-mixtral-8x7b',
    name: 'Mixtral 8x7B (Groq)',
    provider: 'groq',
    modelId: 'mixtral-8x7b-32768',
    costPer1kTokens: 0.24,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    description: 'Mistral\'s Mixtral on Groq\'s fast inference',
    strengths: ['very-fast', 'cost-effective', 'multilingual'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 14
  },

  // ===== IMAGE GENERATION MODELS =====
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'openai',
    modelId: 'dall-e-3',
    costPer1kTokens: 40.0, // ~$0.04 per image (standard), treating as tokens
    maxTokens: 4000, // Prompt max
    contextWindow: 4000,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'OpenAI\'s most advanced image generation model',
    strengths: ['photorealistic', 'creative', 'high-quality', 'vivid'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'dall-e-2',
    name: 'DALL-E 2',
    provider: 'openai',
    modelId: 'dall-e-2',
    costPer1kTokens: 16.0, // ~$0.016-0.02 per image
    maxTokens: 1000,
    contextWindow: 1000,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'OpenAI\'s efficient image generation model',
    strengths: ['fast', 'affordable', 'variations', 'edits'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    provider: 'stability',
    modelId: 'stable-diffusion-xl-1024-v1-0',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    costPer1kTokens: 6.5, // ~$0.0065 per image
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'High-quality open-source image generation',
    strengths: ['photorealistic', 'artistic', 'controllable', 'affordable'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 3
  },
  {
    id: 'sdxl-turbo',
    name: 'SDXL Turbo',
    provider: 'stability',
    modelId: 'stable-diffusion-xl-1024-v1-0',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    costPer1kTokens: 2.0, // Very affordable
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Ultra-fast image generation',
    strengths: ['ultra-fast', 'real-time', 'affordable'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 4
  },

  // ===== AUDIO MODELS (Speech-to-Text) =====
  {
    id: 'whisper-1',
    name: 'Whisper',
    provider: 'openai',
    modelId: 'whisper-1',
    costPer1kTokens: 6.0, // $0.006 per minute
    maxTokens: 25000, // ~25 minutes of audio
    contextWindow: 25000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'OpenAI\'s powerful speech recognition model',
    strengths: ['multilingual', 'accurate', 'timestamps', 'translation'],
    languages: ['en', 'es', 'fr', 'de', 'it', 'ja', 'ko', 'zh', 'pt', 'nl', 'ru', 'ar', 'hi'],
    category: 'AUDIO_STT',
    tier: 'BASIC',
    priority: 1
  },

  // ===== AUDIO MODELS (Text-to-Speech) =====
  {
    id: 'tts-1',
    name: 'TTS-1',
    provider: 'openai',
    modelId: 'tts-1',
    costPer1kTokens: 15.0, // $0.015 per 1K characters
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'OpenAI\'s fast text-to-speech model',
    strengths: ['fast', 'natural', 'multiple-voices'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 2
  },
  {
    id: 'tts-1-hd',
    name: 'TTS-1 HD',
    provider: 'openai',
    modelId: 'tts-1-hd',
    costPer1kTokens: 30.0, // $0.030 per 1K characters
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'OpenAI\'s high-definition text-to-speech model',
    strengths: ['high-quality', 'natural', 'studio-grade'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'elevenlabs-multilingual',
    name: 'ElevenLabs Multilingual v2',
    provider: 'elevenlabs',
    modelId: 'eleven_multilingual_v2',
    apiUrl: 'https://api.elevenlabs.io/v1/text-to-speech',
    costPer1kTokens: 18.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Premium multilingual voice synthesis',
    strengths: ['ultra-realistic', 'voice-cloning', 'emotional'],
    languages: ['en', 'de', 'pl', 'es', 'it', 'fr', 'pt', 'hi', 'ar', 'zh', 'ja', 'ko'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 3
  },

  // ===== EMBEDDING MODELS =====
  {
    id: 'text-embedding-3-small',
    name: 'Text Embedding 3 Small',
    provider: 'openai',
    modelId: 'text-embedding-3-small',
    costPer1kTokens: 0.02, // $0.00002 per 1K tokens
    maxTokens: 8191,
    contextWindow: 8191,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Efficient text embedding model for semantic search',
    strengths: ['fast', 'affordable', '1536-dimensions'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 1
  },
  {
    id: 'text-embedding-3-large',
    name: 'Text Embedding 3 Large',
    provider: 'openai',
    modelId: 'text-embedding-3-large',
    costPer1kTokens: 0.13, // $0.00013 per 1K tokens
    maxTokens: 8191,
    contextWindow: 8191,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'High-accuracy embedding model with configurable dimensions',
    strengths: ['high-accuracy', 'flexible-dimensions', '3072-dimensions'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 2
  },

  // ===== NEW 2024 MODELS =====

  // OpenAI Reasoning Models (o1 series)
  {
    id: 'o1',
    name: 'OpenAI o1',
    provider: 'openai',
    modelId: 'o1',
    costPer1kTokens: 15.0,
    maxTokens: 100000,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenAI advanced reasoning model with chain-of-thought',
    strengths: ['complex-reasoning', 'math', 'coding', 'science'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'o1-mini',
    name: 'OpenAI o1-mini',
    provider: 'openai',
    modelId: 'o1-mini',
    costPer1kTokens: 3.0,
    maxTokens: 65536,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Smaller, faster reasoning model',
    strengths: ['fast-reasoning', 'coding', 'math'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    modelId: 'gpt-4-turbo',
    costPer1kTokens: 10.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'GPT-4 Turbo with vision and improved performance',
    strengths: ['multimodal', 'reasoning', 'vision'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 3
  },

  // Anthropic Claude 3 Full Family
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    modelId: 'claude-3-opus-20240229',
    costPer1kTokens: 15.0,
    maxTokens: 4096,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic most powerful model for complex tasks',
    strengths: ['complex-analysis', 'nuanced', 'creative'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },

  // Google Gemini 2.0
  {
    id: 'gemini-2.0-flash-exp',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    modelId: 'gemini-2.0-flash-exp',
    costPer1kTokens: 0.1,
    maxTokens: 8192,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'Google latest fast multimodal model with native tool use',
    strengths: ['ultra-fast', 'multimodal', 'long-context', 'tool-use'],
    category: 'MULTIMODAL',
    tier: 'BASIC',
    priority: 2
  },
  {
    id: 'gemma-2-27b',
    name: 'Gemma 2 27B',
    provider: 'google',
    modelId: 'gemma-2-27b-it',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    modelSize: '27B',
    description: 'Google open-source lightweight LLM',
    strengths: ['open-source', 'efficient', 'instruction-following'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 15
  },

  // DeepSeek Models
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    modelId: 'deepseek-chat',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.14,
    maxTokens: 8192,
    contextWindow: 64000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '671B',
    description: 'DeepSeek V3 MoE model - competitive with GPT-4',
    strengths: ['cost-effective', 'reasoning', 'coding', 'multilingual'],
    category: 'REASONING',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    modelId: 'deepseek-reasoner',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.55,
    maxTokens: 8192,
    contextWindow: 64000,
    supportsChat: true,
    supportsCode: true,
    description: 'DeepSeek advanced reasoning model',
    strengths: ['chain-of-thought', 'math', 'complex-reasoning'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 3
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'deepseek',
    modelId: 'deepseek-coder',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.14,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'DeepSeek specialized coding model',
    strengths: ['code-generation', 'debugging', 'code-completion'],
    category: 'CODE',
    tier: 'BASIC',
    priority: 4
  },

  // xAI Grok Models
  {
    id: 'grok-2',
    name: 'Grok-2',
    provider: 'xai',
    modelId: 'grok-2-latest',
    apiUrl: 'https://api.x.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 131072,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'xAI flagship model with real-time knowledge',
    strengths: ['current-events', 'reasoning', 'humor', 'long-context'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 5
  },
  {
    id: 'grok-beta',
    name: 'Grok Beta',
    provider: 'xai',
    modelId: 'grok-beta',
    apiUrl: 'https://api.x.ai/v1/chat/completions',
    costPer1kTokens: 5.0,
    maxTokens: 131072,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Grok with vision capabilities',
    strengths: ['multimodal', 'vision', 'analysis'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 6
  },

  // Meta Llama 3.x (via Together/Groq)
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'together',
    modelId: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.88,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '70B',
    description: 'Meta latest Llama model with multilingual support',
    strengths: ['multilingual', 'reasoning', 'instruction-following'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 8
  },
  {
    id: 'llama-3.2-90b-vision',
    name: 'Llama 3.2 90B Vision',
    provider: 'together',
    modelId: 'meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 1.2,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    modelSize: '90B',
    description: 'Meta first multimodal Llama with vision',
    strengths: ['vision', 'image-understanding', 'multimodal'],
    category: 'VISION',
    tier: 'PREMIUM',
    priority: 7
  },
  {
    id: 'llama-3.1-405b',
    name: 'Llama 3.1 405B',
    provider: 'together',
    modelId: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 3.5,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    modelSize: '405B',
    description: 'Meta largest open-source model',
    strengths: ['highest-quality', 'complex-tasks', 'reasoning'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 4
  },

  // Mistral Official Models
  {
    id: 'mistral-large-2411',
    name: 'Mistral Large (Nov 2024)',
    provider: 'mistral',
    modelId: 'mistral-large-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Mistral top-tier model for complex tasks',
    strengths: ['reasoning', 'multilingual', 'function-calling'],
    languages: ['en', 'fr', 'de', 'es', 'it', 'pt', 'ru', 'zh', 'ja', 'ko'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral NeMo',
    provider: 'mistral',
    modelId: 'open-mistral-nemo',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 0.15,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    modelSize: '12B',
    description: 'Open-weight 12B general-purpose model',
    strengths: ['efficient', 'fast', 'general-purpose'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 12
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    provider: 'mistral',
    modelId: 'codestral-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 0.3,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: false,
    supportsCode: true,
    description: 'Mistral specialized code generation model',
    strengths: ['code-generation', 'fill-in-middle', '80-languages'],
    category: 'CODE',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'pixtral-large',
    name: 'Pixtral Large',
    provider: 'mistral',
    modelId: 'pixtral-large-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Mistral frontier multimodal model',
    strengths: ['vision', 'document-understanding', 'charts'],
    category: 'VISION',
    tier: 'PREMIUM',
    priority: 7
  },

  // Qwen Models (Alibaba)
  {
    id: 'qwen2.5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'together',
    modelId: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 1.2,
    maxTokens: 32768,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    description: 'Alibaba flagship language model',
    strengths: ['multilingual', 'coding', 'math', 'reasoning'],
    languages: ['en', 'zh', 'ja', 'ko', 'de', 'fr', 'es'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'qwq-32b',
    name: 'QwQ 32B Preview',
    provider: 'together',
    modelId: 'Qwen/QwQ-32B-Preview',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.8,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    modelSize: '32B',
    description: 'Qwen experimental reasoning model',
    strengths: ['reasoning', 'chain-of-thought', 'math'],
    category: 'REASONING',
    tier: 'BASIC',
    priority: 10
  },

  // Cohere Models
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    modelId: 'command-r-plus',
    apiUrl: 'https://api.cohere.ai/v1/chat',
    costPer1kTokens: 3.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Cohere flagship RAG-optimized model',
    strengths: ['RAG', 'grounded-generation', 'citations'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 8
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'cohere',
    modelId: 'command-r',
    apiUrl: 'https://api.cohere.ai/v1/chat',
    costPer1kTokens: 0.5,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Cohere efficient RAG model',
    strengths: ['RAG', 'efficient', 'cost-effective'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 12
  },
  {
    id: 'embed-v3.5',
    name: 'Cohere Embed v3.5',
    provider: 'cohere',
    modelId: 'embed-english-v3.0',
    apiUrl: 'https://api.cohere.ai/v1/embed',
    costPer1kTokens: 0.1,
    maxTokens: 512,
    contextWindow: 512,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Cohere state-of-the-art embeddings',
    strengths: ['semantic-search', 'clustering', 'classification'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 3
  },

  // Perplexity Models
  {
    id: 'sonar-huge',
    name: 'Llama 3.1 Sonar Huge',
    provider: 'perplexity',
    modelId: 'llama-3.1-sonar-huge-128k-online',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    costPer1kTokens: 5.0,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Perplexity largest model with web search',
    strengths: ['web-search', 'current-info', 'citations'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'sonar-small',
    name: 'Llama 3.1 Sonar Small',
    provider: 'perplexity',
    modelId: 'llama-3.1-sonar-small-128k-online',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    costPer1kTokens: 0.2,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Perplexity efficient model with web search',
    strengths: ['web-search', 'fast', 'affordable'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 10
  },

  // Fireworks AI
  {
    id: 'fireworks-llama-3.1-405b',
    name: 'Llama 3.1 405B (Fireworks)',
    provider: 'fireworks',
    modelId: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
    apiUrl: 'https://api.fireworks.ai/inference/v1/chat/completions',
    costPer1kTokens: 3.0,
    maxTokens: 16384,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Llama 3.1 405B on Fireworks fast inference',
    strengths: ['fast-inference', 'high-quality', 'long-context'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 5
  }
];

// Validate and create the final models array with defaults
export const ALL_MODELS: Model[] = RAW_MODELS.map(model =>
  ModelSchema.parse(model)
);

// Environment variable mappings for API keys
export const API_KEY_MAPPINGS = {
  // Major LLM providers
  openai: 'OPENAI_API_KEY',
  anthropic: 'ANTHROPIC_API_KEY',
  google: 'GOOGLE_API_KEY',
  cohere: 'COHERE_API_KEY',
  mistral: 'MISTRAL_API_KEY',
  meta: 'META_API_KEY',
  huggingface: 'HUGGINGFACE_API_KEY',
  ollama: 'OLLAMA_API_KEY',
  together: 'TOGETHER_API_KEY',
  perplexity: 'PERPLEXITY_API_KEY',
  groq: 'GROQ_API_KEY',
  replicate: 'REPLICATE_API_KEY',
  stability: 'STABILITY_API_KEY',
  midjourney: 'MIDJOURNEY_API_KEY',
  runpod: 'RUNPOD_API_KEY',
  // New LLM providers (2024)
  deepseek: 'DEEPSEEK_API_KEY',
  xai: 'XAI_API_KEY',
  fireworks: 'FIREWORKS_API_KEY',
  openrouter: 'OPENROUTER_API_KEY',
  anyscale: 'ANYSCALE_API_KEY',
  nvidia: 'NVIDIA_API_KEY',
  qwen: 'QWEN_API_KEY',
  // Specialized audio/media providers
  elevenlabs: 'ELEVENLABS_API_KEY',
  assemblyai: 'ASSEMBLYAI_API_KEY',
  deepgram: 'DEEPGRAM_API_KEY',
  suno: 'SUNO_API_KEY',
  runway: 'RUNWAY_API_KEY'
} as const;

// Model categories for routing
export const MODEL_CATEGORIES = {
  // Text-based categories
  CHAT: 'Conversational AI and general queries',
  CODE: 'Code generation and programming assistance',
  REASONING: 'Complex reasoning and analysis',
  CREATIVE: 'Creative writing and content generation',
  FAST: 'Quick responses and real-time applications',
  VISION: 'Image and visual content analysis',
  MULTIMODAL: 'Multi-format content processing',

  // Generation categories
  IMAGE_GEN: 'AI image generation (DALL-E, Stable Diffusion, Midjourney)',
  VIDEO_GEN: 'AI video generation and editing',

  // Audio categories
  AUDIO_STT: 'Speech-to-text transcription (Whisper)',
  AUDIO_TTS: 'Text-to-speech synthesis',

  // Utility categories
  EMBEDDING: 'Text embeddings for semantic search and RAG'
} as const;

export type ModelProvider = keyof typeof API_KEY_MAPPINGS;
export type ModelCategory = keyof typeof MODEL_CATEGORIES;