import { z } from 'zod';

// Core model configuration schema
export const ModelSchema = z.object({
  id: z.string(),
  name: z.string(),
  provider: z.enum([
    // Major LLM providers
    'openai', 'anthropic', 'google', 'cohere', 'mistral', 'meta',
    'huggingface', 'ollama', 'together', 'perplexity', 'groq',
    'replicate', 'stability', 'midjourney', 'runpod',
    // New LLM providers (2024)
    'deepseek', 'xai', 'fireworks', 'openrouter', 'anyscale', 'nvidia', 'qwen',
    // Specialized audio/media providers
    'elevenlabs', 'assemblyai', 'deepgram', 'suno', 'runway',
    // Fast LLM inference (2025)
    'cerebras', 'sambanova',
    // Enterprise LLM
    'ai21',
    // Embeddings specialists
    'voyage', 'jina',
    // Image generation (2025)
    'blackforest', 'ideogram', 'leonardo', 'recraft',
    // Video generation
    'pika', 'luma', 'kling', 'synthesia', 'heygen',
    // TTS specialists
    'playht', 'murf', 'resemble', 'speechify',
    // Music generation
    'udio', 'riffusion'
  ]),
  modelId: z.string(),
  apiUrl: z.string().optional(),
  apiKey: z.string().optional(),
  apiKeys: z.array(z.string()).optional(), // Support for multiple API keys per provider
  currentKeyIndex: z.number().default(0), // For key rotation
  keyRotationEnabled: z.boolean().default(false),
  costPer1kTokens: z.number().default(0),
  maxTokens: z.number().default(4096),
  contextWindow: z.number().default(4096),
  supportsChat: z.boolean().default(true),
  supportsCode: z.boolean().default(true),
  supportsVision: z.boolean().default(false),
  supportsFiles: z.boolean().default(false),
  supportsStreaming: z.boolean().default(false),
  modelSize: z.string().optional(),
  description: z.string().optional(),
  strengths: z.array(z.string()).default([]),
  languages: z.array(z.string()).default(['en']),
  enabled: z.boolean().default(true),
  priority: z.number().default(50),
  category: z.enum([
    'CHAT', 'CODE', 'REASONING', 'CREATIVE', 'FAST', 'VISION', 'MULTIMODAL',
    'IMAGE_GEN', 'VIDEO_GEN', 'AUDIO_STT', 'AUDIO_TTS', 'EMBEDDING'
  ]).default('CHAT'),
  tier: z.enum(['FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE']).default('FREE'),
  // New capability flags
  supportsImageGen: z.boolean().default(false),
  supportsAudioInput: z.boolean().default(false),
  supportsAudioOutput: z.boolean().default(false),
  supportsEmbeddings: z.boolean().default(false)
});

export type Model = z.infer<typeof ModelSchema>;

// Raw model configurations that will be validated and filled with defaults
const RAW_MODELS = [
  // ===== OPEN SOURCE MODELS (FREE) =====

  // Meta Llama Models (HuggingFace)
  {
    id: 'llama-2-7b-chat',
    name: 'Llama 3.2 3B Chat',
    provider: 'huggingface',
    modelId: 'meta-llama/Llama-3.2-3B-Instruct',
    apiUrl: 'https://api-inference.huggingface.co/models/meta-llama/Llama-3.2-3B-Instruct',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: true,
    supportsCode: true,
    modelSize: '3B',
    description: 'Meta\'s Llama 3.2 model optimized for conversations',
    strengths: ['conversational', 'general-purpose', 'fast'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 10
  },
  {
    id: 'llama-2-13b-chat',
    name: 'Llama 3.2 1B Chat',
    provider: 'huggingface',
    modelId: 'meta-llama/Llama-3.2-1B-Instruct',
    apiUrl: 'https://api-inference.huggingface.co/models/meta-llama/Llama-3.2-1B-Instruct',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: true,
    supportsCode: true,
    modelSize: '1B',
    description: 'Smaller Llama 3.2 model for efficient conversations',
    strengths: ['efficient', 'fast', 'lightweight'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 15
  },

  // Code Llama Models
  {
    id: 'code-llama-7b',
    name: 'Code Llama 7B',
    provider: 'huggingface',
    modelId: 'codellama/CodeLlama-7b-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/codellama/CodeLlama-7b-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: true,
    modelSize: '7B',
    description: 'Meta\'s Code Llama for code generation',
    strengths: ['code-generation', 'programming', 'debugging'],
    category: 'CODE',
    tier: 'FREE',
    priority: 5
  },
  {
    id: 'code-llama-13b',
    name: 'Code Llama 13B',
    provider: 'huggingface',
    modelId: 'codellama/CodeLlama-13b-hf',
    apiUrl: 'https://api-inference.huggingface.co/models/codellama/CodeLlama-13b-hf',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: true,
    modelSize: '13B',
    description: 'Larger Code Llama for complex programming tasks',
    strengths: ['complex-code', 'architecture', 'algorithms'],
    category: 'CODE',
    tier: 'FREE',
    priority: 8
  },

  // Mistral Models
  {
    id: 'mistral-7b-instruct',
    name: 'Mistral 7B Instruct',
    provider: 'huggingface',
    modelId: 'mistralai/Mistral-7B-Instruct-v0.1',
    apiUrl: 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    modelSize: '7B',
    description: 'Mistral\'s efficient instruct model',
    strengths: ['multilingual', 'efficient', 'instruction-following'],
    languages: ['en', 'fr', 'de', 'es', 'it'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 12
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'huggingface',
    modelId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    apiUrl: 'https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1',
    costPer1kTokens: 0,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    modelSize: '8x7B',
    description: 'Mistral\'s mixture of experts model',
    strengths: ['high-quality', 'multilingual', 'reasoning'],
    languages: ['en', 'fr', 'de', 'es', 'it'],
    category: 'REASONING',
    tier: 'FREE',
    priority: 18
  },

  // Other Open Source Models
  {
    id: 'starcoder',
    name: 'StarCoder',
    provider: 'huggingface',
    modelId: 'bigcode/starcoder',
    apiUrl: 'https://api-inference.huggingface.co/models/bigcode/starcoder',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: true,
    modelSize: '15.5B',
    description: 'BigCode\'s advanced code generation model',
    strengths: ['code-completion', 'multiple-languages', 'advanced-programming'],
    category: 'CODE',
    tier: 'FREE',
    priority: 20
  },
  {
    id: 'flan-t5-xl',
    name: 'Flan-T5 XL',
    provider: 'huggingface',
    modelId: 'google/flan-t5-xl',
    apiUrl: 'https://api-inference.huggingface.co/models/google/flan-t5-xl',
    costPer1kTokens: 0,
    maxTokens: 512,
    contextWindow: 512,
    supportsChat: true,
    supportsCode: false,
    modelSize: '3B',
    description: 'Google\'s instruction-tuned T5 model',
    strengths: ['question-answering', 'instructions', 'factual'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 25
  },
  {
    id: 'phi-2',
    name: 'Microsoft Phi-2',
    provider: 'huggingface',
    modelId: 'microsoft/phi-2',
    apiUrl: 'https://api-inference.huggingface.co/models/microsoft/phi-2',
    costPer1kTokens: 0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: true,
    supportsCode: true,
    modelSize: '2.7B',
    description: 'Microsoft\'s small but capable model',
    strengths: ['fast', 'efficient', 'general-purpose'],
    category: 'FAST',
    tier: 'FREE',
    priority: 6
  },
  {
    id: 'gpt2',
    name: 'GPT-2',
    provider: 'huggingface',
    modelId: 'gpt2',
    apiUrl: 'https://api-inference.huggingface.co/models/gpt2',
    costPer1kTokens: 0,
    maxTokens: 1024,
    contextWindow: 1024,
    supportsChat: true,
    supportsCode: false,
    modelSize: '124M',
    description: 'OpenAI\'s GPT-2 (reliable fallback)',
    strengths: ['reliable', 'fast', 'always-available'],
    category: 'FAST',
    tier: 'FREE',
    priority: 100 // Fallback model
  },

  // ===== PAID MODELS =====

  // OpenAI Models
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    modelId: 'gpt-4o',
    costPer1kTokens: 5.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    supportsStreaming: true,
    description: 'OpenAI\'s most advanced multimodal model',
    strengths: ['multimodal', 'reasoning', 'vision', 'highest-quality'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    modelId: 'gpt-4o-mini',
    costPer1kTokens: 0.15,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenAI\'s efficient and affordable model',
    strengths: ['cost-effective', 'fast', 'multimodal'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 3
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    modelId: 'gpt-3.5-turbo',
    costPer1kTokens: 0.5,
    maxTokens: 4096,
    contextWindow: 16385,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'OpenAI\'s fast and affordable model',
    strengths: ['fast', 'affordable', 'reliable'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 7
  },

  // Anthropic Models
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    costPer1kTokens: 3.0,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic\'s most advanced model',
    strengths: ['reasoning', 'analysis', 'safety', 'long-context'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'anthropic',
    modelId: 'claude-3-haiku-20240307',
    costPer1kTokens: 0.25,
    maxTokens: 4096,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Anthropic\'s fast and efficient model',
    strengths: ['fast', 'efficient', 'cost-effective'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 4
  },

  // Google Models
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    modelId: 'gemini-1.5-pro',
    costPer1kTokens: 7.0,
    maxTokens: 8192,
    contextWindow: 2000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Google\'s advanced multimodal model',
    strengths: ['multimodal', 'very-long-context', 'reasoning'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    modelId: 'gemini-1.5-flash',
    costPer1kTokens: 0.075,
    maxTokens: 8192,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Google\'s fast multimodal model',
    strengths: ['fast', 'multimodal', 'long-context'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 11
  },

  // Groq Models (Fast Inference)
  {
    id: 'groq-llama-3-70b',
    name: 'Llama 3 70B (Groq)',
    provider: 'groq',
    modelId: 'llama3-70b-8192',
    costPer1kTokens: 0.59,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    description: 'Meta\'s Llama 3 on Groq\'s fast inference',
    strengths: ['very-fast', 'high-quality', 'reasoning'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 13
  },
  {
    id: 'groq-mixtral-8x7b',
    name: 'Mixtral 8x7B (Groq)',
    provider: 'groq',
    modelId: 'mixtral-8x7b-32768',
    costPer1kTokens: 0.24,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    description: 'Mistral\'s Mixtral on Groq\'s fast inference',
    strengths: ['very-fast', 'cost-effective', 'multilingual'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 14
  },

  // ===== IMAGE GENERATION MODELS =====
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'openai',
    modelId: 'dall-e-3',
    costPer1kTokens: 40.0, // ~$0.04 per image (standard), treating as tokens
    maxTokens: 4000, // Prompt max
    contextWindow: 4000,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'OpenAI\'s most advanced image generation model',
    strengths: ['photorealistic', 'creative', 'high-quality', 'vivid'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'dall-e-2',
    name: 'DALL-E 2',
    provider: 'openai',
    modelId: 'dall-e-2',
    costPer1kTokens: 16.0, // ~$0.016-0.02 per image
    maxTokens: 1000,
    contextWindow: 1000,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'OpenAI\'s efficient image generation model',
    strengths: ['fast', 'affordable', 'variations', 'edits'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    provider: 'stability',
    modelId: 'stable-diffusion-xl-1024-v1-0',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    costPer1kTokens: 6.5, // ~$0.0065 per image
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'High-quality open-source image generation',
    strengths: ['photorealistic', 'artistic', 'controllable', 'affordable'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 3
  },
  {
    id: 'sdxl-turbo',
    name: 'SDXL Turbo',
    provider: 'stability',
    modelId: 'stable-diffusion-xl-1024-v1-0',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    costPer1kTokens: 2.0, // Very affordable
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Ultra-fast image generation',
    strengths: ['ultra-fast', 'real-time', 'affordable'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 4
  },

  // ===== AUDIO MODELS (Speech-to-Text) =====
  {
    id: 'whisper-1',
    name: 'Whisper',
    provider: 'openai',
    modelId: 'whisper-1',
    costPer1kTokens: 6.0, // $0.006 per minute
    maxTokens: 25000, // ~25 minutes of audio
    contextWindow: 25000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'OpenAI\'s powerful speech recognition model',
    strengths: ['multilingual', 'accurate', 'timestamps', 'translation'],
    languages: ['en', 'es', 'fr', 'de', 'it', 'ja', 'ko', 'zh', 'pt', 'nl', 'ru', 'ar', 'hi'],
    category: 'AUDIO_STT',
    tier: 'BASIC',
    priority: 1
  },

  // ===== AUDIO MODELS (Text-to-Speech) =====
  {
    id: 'tts-1',
    name: 'TTS-1',
    provider: 'openai',
    modelId: 'tts-1',
    costPer1kTokens: 15.0, // $0.015 per 1K characters
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'OpenAI\'s fast text-to-speech model',
    strengths: ['fast', 'natural', 'multiple-voices'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 2
  },
  {
    id: 'tts-1-hd',
    name: 'TTS-1 HD',
    provider: 'openai',
    modelId: 'tts-1-hd',
    costPer1kTokens: 30.0, // $0.030 per 1K characters
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'OpenAI\'s high-definition text-to-speech model',
    strengths: ['high-quality', 'natural', 'studio-grade'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'elevenlabs-multilingual',
    name: 'ElevenLabs Multilingual v2',
    provider: 'elevenlabs',
    modelId: 'eleven_multilingual_v2',
    apiUrl: 'https://api.elevenlabs.io/v1/text-to-speech',
    costPer1kTokens: 18.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Premium multilingual voice synthesis',
    strengths: ['ultra-realistic', 'voice-cloning', 'emotional'],
    languages: ['en', 'de', 'pl', 'es', 'it', 'fr', 'pt', 'hi', 'ar', 'zh', 'ja', 'ko'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 3
  },

  // ===== EMBEDDING MODELS =====
  {
    id: 'text-embedding-3-small',
    name: 'Text Embedding 3 Small',
    provider: 'openai',
    modelId: 'text-embedding-3-small',
    costPer1kTokens: 0.02, // $0.00002 per 1K tokens
    maxTokens: 8191,
    contextWindow: 8191,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Efficient text embedding model for semantic search',
    strengths: ['fast', 'affordable', '1536-dimensions'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 1
  },
  {
    id: 'text-embedding-3-large',
    name: 'Text Embedding 3 Large',
    provider: 'openai',
    modelId: 'text-embedding-3-large',
    costPer1kTokens: 0.13, // $0.00013 per 1K tokens
    maxTokens: 8191,
    contextWindow: 8191,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'High-accuracy embedding model with configurable dimensions',
    strengths: ['high-accuracy', 'flexible-dimensions', '3072-dimensions'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 2
  },

  // ===== NEW 2024 MODELS =====

  // OpenAI Reasoning Models (o1 series)
  {
    id: 'o1',
    name: 'OpenAI o1',
    provider: 'openai',
    modelId: 'o1',
    costPer1kTokens: 15.0,
    maxTokens: 100000,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenAI advanced reasoning model with chain-of-thought',
    strengths: ['complex-reasoning', 'math', 'coding', 'science'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'o1-mini',
    name: 'OpenAI o1-mini',
    provider: 'openai',
    modelId: 'o1-mini',
    costPer1kTokens: 3.0,
    maxTokens: 65536,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Smaller, faster reasoning model',
    strengths: ['fast-reasoning', 'coding', 'math'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    modelId: 'gpt-4-turbo',
    costPer1kTokens: 10.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'GPT-4 Turbo with vision and improved performance',
    strengths: ['multimodal', 'reasoning', 'vision'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 3
  },

  // Anthropic Claude 3 Full Family
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    modelId: 'claude-3-opus-20240229',
    costPer1kTokens: 15.0,
    maxTokens: 4096,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic most powerful model for complex tasks',
    strengths: ['complex-analysis', 'nuanced', 'creative'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },

  // Google Gemini 2.0
  {
    id: 'gemini-2.0-flash-exp',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    modelId: 'gemini-2.0-flash-exp',
    costPer1kTokens: 0.1,
    maxTokens: 8192,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'Google latest fast multimodal model with native tool use',
    strengths: ['ultra-fast', 'multimodal', 'long-context', 'tool-use'],
    category: 'MULTIMODAL',
    tier: 'BASIC',
    priority: 2
  },
  {
    id: 'gemma-2-27b',
    name: 'Gemma 2 27B',
    provider: 'google',
    modelId: 'gemma-2-27b-it',
    costPer1kTokens: 0,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    modelSize: '27B',
    description: 'Google open-source lightweight LLM',
    strengths: ['open-source', 'efficient', 'instruction-following'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 15
  },

  // DeepSeek Models
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    modelId: 'deepseek-chat',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.14,
    maxTokens: 8192,
    contextWindow: 64000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '671B',
    description: 'DeepSeek V3 MoE model - competitive with GPT-4',
    strengths: ['cost-effective', 'reasoning', 'coding', 'multilingual'],
    category: 'REASONING',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    modelId: 'deepseek-reasoner',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.55,
    maxTokens: 8192,
    contextWindow: 64000,
    supportsChat: true,
    supportsCode: true,
    description: 'DeepSeek advanced reasoning model',
    strengths: ['chain-of-thought', 'math', 'complex-reasoning'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 3
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'deepseek',
    modelId: 'deepseek-coder',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.14,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'DeepSeek specialized coding model',
    strengths: ['code-generation', 'debugging', 'code-completion'],
    category: 'CODE',
    tier: 'BASIC',
    priority: 4
  },

  // xAI Grok Models
  {
    id: 'grok-2',
    name: 'Grok-2',
    provider: 'xai',
    modelId: 'grok-2-latest',
    apiUrl: 'https://api.x.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 131072,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'xAI flagship model with real-time knowledge',
    strengths: ['current-events', 'reasoning', 'humor', 'long-context'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 5
  },
  {
    id: 'grok-beta',
    name: 'Grok Beta',
    provider: 'xai',
    modelId: 'grok-beta',
    apiUrl: 'https://api.x.ai/v1/chat/completions',
    costPer1kTokens: 5.0,
    maxTokens: 131072,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Grok with vision capabilities',
    strengths: ['multimodal', 'vision', 'analysis'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 6
  },

  // Meta Llama 3.x (via Together/Groq)
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'together',
    modelId: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.88,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '70B',
    description: 'Meta latest Llama model with multilingual support',
    strengths: ['multilingual', 'reasoning', 'instruction-following'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 8
  },
  {
    id: 'llama-3.2-90b-vision',
    name: 'Llama 3.2 90B Vision',
    provider: 'together',
    modelId: 'meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 1.2,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    modelSize: '90B',
    description: 'Meta first multimodal Llama with vision',
    strengths: ['vision', 'image-understanding', 'multimodal'],
    category: 'VISION',
    tier: 'PREMIUM',
    priority: 7
  },
  {
    id: 'llama-3.1-405b',
    name: 'Llama 3.1 405B',
    provider: 'together',
    modelId: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 3.5,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    modelSize: '405B',
    description: 'Meta largest open-source model',
    strengths: ['highest-quality', 'complex-tasks', 'reasoning'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 4
  },

  // Mistral Official Models
  {
    id: 'mistral-large-2411',
    name: 'Mistral Large (Nov 2024)',
    provider: 'mistral',
    modelId: 'mistral-large-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Mistral top-tier model for complex tasks',
    strengths: ['reasoning', 'multilingual', 'function-calling'],
    languages: ['en', 'fr', 'de', 'es', 'it', 'pt', 'ru', 'zh', 'ja', 'ko'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral NeMo',
    provider: 'mistral',
    modelId: 'open-mistral-nemo',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 0.15,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    modelSize: '12B',
    description: 'Open-weight 12B general-purpose model',
    strengths: ['efficient', 'fast', 'general-purpose'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 12
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    provider: 'mistral',
    modelId: 'codestral-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 0.3,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: false,
    supportsCode: true,
    description: 'Mistral specialized code generation model',
    strengths: ['code-generation', 'fill-in-middle', '80-languages'],
    category: 'CODE',
    tier: 'BASIC',
    priority: 5
  },
  {
    id: 'pixtral-large',
    name: 'Pixtral Large',
    provider: 'mistral',
    modelId: 'pixtral-large-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 32768,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Mistral frontier multimodal model',
    strengths: ['vision', 'document-understanding', 'charts'],
    category: 'VISION',
    tier: 'PREMIUM',
    priority: 7
  },

  // Qwen Models (Alibaba)
  {
    id: 'qwen2.5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'together',
    modelId: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 1.2,
    maxTokens: 32768,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    description: 'Alibaba flagship language model',
    strengths: ['multilingual', 'coding', 'math', 'reasoning'],
    languages: ['en', 'zh', 'ja', 'ko', 'de', 'fr', 'es'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'qwq-32b',
    name: 'QwQ 32B Preview',
    provider: 'together',
    modelId: 'Qwen/QwQ-32B-Preview',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.8,
    maxTokens: 32768,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    modelSize: '32B',
    description: 'Qwen experimental reasoning model',
    strengths: ['reasoning', 'chain-of-thought', 'math'],
    category: 'REASONING',
    tier: 'BASIC',
    priority: 10
  },

  // Cohere Models
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    modelId: 'command-r-plus',
    apiUrl: 'https://api.cohere.ai/v1/chat',
    costPer1kTokens: 3.0,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Cohere flagship RAG-optimized model',
    strengths: ['RAG', 'grounded-generation', 'citations'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 8
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'cohere',
    modelId: 'command-r',
    apiUrl: 'https://api.cohere.ai/v1/chat',
    costPer1kTokens: 0.5,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Cohere efficient RAG model',
    strengths: ['RAG', 'efficient', 'cost-effective'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 12
  },
  {
    id: 'embed-v3.5',
    name: 'Cohere Embed v3.5',
    provider: 'cohere',
    modelId: 'embed-english-v3.0',
    apiUrl: 'https://api.cohere.ai/v1/embed',
    costPer1kTokens: 0.1,
    maxTokens: 512,
    contextWindow: 512,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Cohere state-of-the-art embeddings',
    strengths: ['semantic-search', 'clustering', 'classification'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 3
  },

  // Perplexity Models
  {
    id: 'sonar-huge',
    name: 'Llama 3.1 Sonar Huge',
    provider: 'perplexity',
    modelId: 'llama-3.1-sonar-huge-128k-online',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    costPer1kTokens: 5.0,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Perplexity largest model with web search',
    strengths: ['web-search', 'current-info', 'citations'],
    category: 'CHAT',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'sonar-small',
    name: 'Llama 3.1 Sonar Small',
    provider: 'perplexity',
    modelId: 'llama-3.1-sonar-small-128k-online',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    costPer1kTokens: 0.2,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'Perplexity efficient model with web search',
    strengths: ['web-search', 'fast', 'affordable'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 10
  },

  // Fireworks AI
  {
    id: 'fireworks-llama-3.1-405b',
    name: 'Llama 3.1 405B (Fireworks)',
    provider: 'fireworks',
    modelId: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
    apiUrl: 'https://api.fireworks.ai/inference/v1/chat/completions',
    costPer1kTokens: 3.0,
    maxTokens: 16384,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Llama 3.1 405B on Fireworks fast inference',
    strengths: ['fast-inference', 'high-quality', 'long-context'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 5
  },

  // ===== PHASE 1: FAST LLM INFERENCE (2025) =====

  // Cerebras (fast inference, OpenAI-compatible)
  {
    id: 'cerebras-llama-3.3-70b',
    name: 'Llama 3.3 70B (Cerebras)',
    provider: 'cerebras',
    modelId: 'llama3.3-70b',
    apiUrl: 'https://api.cerebras.ai/v1/chat/completions',
    costPer1kTokens: 0.6,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '70B',
    description: 'Llama 3.3 70B on Cerebras ultra-fast inference',
    strengths: ['ultra-fast', 'high-throughput', 'cost-effective'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 13
  },
  {
    id: 'cerebras-llama-3.1-8b',
    name: 'Llama 3.1 8B (Cerebras)',
    provider: 'cerebras',
    modelId: 'llama3.1-8b',
    apiUrl: 'https://api.cerebras.ai/v1/chat/completions',
    costPer1kTokens: 0.1,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '8B',
    description: 'Llama 3.1 8B on Cerebras — fastest inference available',
    strengths: ['fastest', 'real-time', 'lightweight'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 17
  },

  // Sambanova (fast inference, OpenAI-compatible)
  {
    id: 'sambanova-llama-3.1-70b',
    name: 'Llama 3.1 70B (Sambanova)',
    provider: 'sambanova',
    modelId: 'Meta-Llama-3.1-70B-Instruct',
    apiUrl: 'https://api.sambanova.ai/v1/chat/completions',
    costPer1kTokens: 0.8,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '70B',
    description: 'Llama 3.1 70B on Sambanova Cloud',
    strengths: ['fast-inference', 'high-quality', 'long-context'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 14
  },
  {
    id: 'sambanova-llama-3.1-8b',
    name: 'Llama 3.1 8B (Sambanova)',
    provider: 'sambanova',
    modelId: 'Meta-Llama-3.1-8B-Instruct',
    apiUrl: 'https://api.sambanova.ai/v1/chat/completions',
    costPer1kTokens: 0.1,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    modelSize: '8B',
    description: 'Llama 3.1 8B on Sambanova',
    strengths: ['fast', 'efficient', 'affordable'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 18
  },

  // ===== ENTERPRISE LLM =====

  // AI21 Jamba Models
  {
    id: 'jamba-1.5-large',
    name: 'Jamba 1.5 Large',
    provider: 'ai21',
    modelId: 'jamba-1.5-large',
    apiUrl: 'https://api.ai21.com/studio/v1/chat/completions',
    costPer1kTokens: 2.0,
    maxTokens: 4096,
    contextWindow: 256000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'AI21 hybrid SSM-Transformer model with 256K context',
    strengths: ['long-context', 'reasoning', 'enterprise'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 11
  },
  {
    id: 'jamba-1.5-mini',
    name: 'Jamba 1.5 Mini',
    provider: 'ai21',
    modelId: 'jamba-1.5-mini',
    apiUrl: 'https://api.ai21.com/studio/v1/chat/completions',
    costPer1kTokens: 0.2,
    maxTokens: 4096,
    contextWindow: 256000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'AI21 efficient Jamba model',
    strengths: ['long-context', 'fast', 'cost-effective'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 15
  },

  // ===== EMBEDDINGS SPECIALISTS =====

  // Voyage AI Embeddings
  {
    id: 'voyage-3-large',
    name: 'Voyage 3 Large',
    provider: 'voyage',
    modelId: 'voyage-3-large',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.14,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage flagship embedding model — 2048 dimensions',
    strengths: ['high-accuracy', '2048-dimensions', '32K-context'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'voyage-3-lite',
    name: 'Voyage 3 Lite',
    provider: 'voyage',
    modelId: 'voyage-3-lite',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.02,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage efficient embedding — 512 dimensions',
    strengths: ['affordable', 'fast', '512-dimensions'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 4
  },
  {
    id: 'voyage-code-3',
    name: 'Voyage Code 3',
    provider: 'voyage',
    modelId: 'voyage-code-3',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.14,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage embedding optimized for code search',
    strengths: ['code-search', 'code-retrieval', 'semantic-code'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 5
  },
  {
    id: 'voyage-finance-2',
    name: 'Voyage Finance 2',
    provider: 'voyage',
    modelId: 'voyage-finance-2',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.14,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage embedding for financial domain',
    strengths: ['finance-domain', 'financial-search', 'domain-optimized'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'voyage-law-2',
    name: 'Voyage Law 2',
    provider: 'voyage',
    modelId: 'voyage-law-2',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.14,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage embedding for legal domain',
    strengths: ['legal-domain', 'legal-search', 'domain-optimized'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'voyage-multilingual-2',
    name: 'Voyage Multilingual 2',
    provider: 'voyage',
    modelId: 'voyage-multilingual-2',
    apiUrl: 'https://api.voyageai.com/v1/embeddings',
    costPer1kTokens: 0.14,
    maxTokens: 32000,
    contextWindow: 32000,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Voyage embedding for multilingual search',
    strengths: ['multilingual', 'cross-lingual', 'translation-search'],
    languages: ['en', 'zh', 'ja', 'ko', 'de', 'fr', 'es', 'ar', 'hi', 'ru'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 5
  },

  // Jina AI Embeddings + Reranking
  {
    id: 'jina-embeddings-v3',
    name: 'Jina Embeddings v3',
    provider: 'jina',
    modelId: 'jina-embeddings-v3',
    apiUrl: 'https://api.jina.ai/v1/embeddings',
    costPer1kTokens: 0.02,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Jina multilingual embedding model — task-specific LoRA',
    strengths: ['multilingual', 'task-specific', '8192-context'],
    languages: ['en', 'zh', 'de', 'es', 'fr', 'ja', 'ko', 'ar', 'ru'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 7
  },
  {
    id: 'jina-clip-v2',
    name: 'Jina CLIP v2',
    provider: 'jina',
    modelId: 'jina-clip-v2',
    apiUrl: 'https://api.jina.ai/v1/embeddings',
    costPer1kTokens: 0.02,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: false,
    supportsVision: true,
    supportsEmbeddings: true,
    description: 'Jina multimodal text+image embedding model',
    strengths: ['multimodal', 'text-image', 'cross-modal-search'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 8
  },
  {
    id: 'jina-colbert-v2',
    name: 'Jina ColBERT v2',
    provider: 'jina',
    modelId: 'jina-colbert-v2',
    apiUrl: 'https://api.jina.ai/v1/embeddings',
    costPer1kTokens: 0.03,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Jina late-interaction embedding for high-precision retrieval',
    strengths: ['late-interaction', 'high-precision', 'token-level'],
    category: 'EMBEDDING',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'jina-reranker-v2',
    name: 'Jina Reranker v2',
    provider: 'jina',
    modelId: 'jina-reranker-v2',
    apiUrl: 'https://api.jina.ai/v1/rerank',
    costPer1kTokens: 0.02,
    maxTokens: 8192,
    contextWindow: 8192,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Jina cross-encoder reranker for search quality',
    strengths: ['reranking', 'relevance-scoring', 'search-quality'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 10
  },

  // ===== IMAGE GENERATION (2025) =====

  // Black Forest Labs (Flux)
  {
    id: 'flux-1.1-pro',
    name: 'Flux 1.1 Pro',
    provider: 'blackforest',
    modelId: 'flux-1.1-pro',
    apiUrl: 'https://api.us1.bfl.ai/v1/flux-1.1-pro',
    costPer1kTokens: 30.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Black Forest Labs fastest Flux model',
    strengths: ['photorealistic', 'fast', 'high-quality', 'prompt-adherence'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'flux-1-pro',
    name: 'Flux 1 Pro',
    provider: 'blackforest',
    modelId: 'flux-1-pro',
    apiUrl: 'https://api.us1.bfl.ai/v1/flux-1-pro',
    costPer1kTokens: 40.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Black Forest Labs flagship image generation',
    strengths: ['best-quality', 'photorealistic', 'professional'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'flux-1-dev',
    name: 'Flux 1 Dev',
    provider: 'blackforest',
    modelId: 'flux-1-dev',
    apiUrl: 'https://api.us1.bfl.ai/v1/flux-1-dev',
    costPer1kTokens: 15.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Flux development model for creative exploration',
    strengths: ['creative', 'experimental', 'artistic'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 6
  },
  {
    id: 'flux-schnell',
    name: 'Flux Schnell',
    provider: 'blackforest',
    modelId: 'flux-schnell',
    apiUrl: 'https://api.us1.bfl.ai/v1/flux-schnell',
    costPer1kTokens: 5.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Ultra-fast Flux model — 1-2 second generation',
    strengths: ['ultra-fast', 'real-time', 'cheapest'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 7
  },

  // Ideogram
  {
    id: 'ideogram-v2',
    name: 'Ideogram v2',
    provider: 'ideogram',
    modelId: 'ideogram-v2',
    costPer1kTokens: 25.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Ideogram v2 with best-in-class text rendering',
    strengths: ['text-rendering', 'typography', 'logos', 'design'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 3
  },
  {
    id: 'ideogram-v2-turbo',
    name: 'Ideogram v2 Turbo',
    provider: 'ideogram',
    modelId: 'ideogram-v2-turbo',
    costPer1kTokens: 8.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Ideogram v2 fast generation with text rendering',
    strengths: ['fast-text-rendering', 'typography', 'design'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 8
  },

  // Leonardo AI
  {
    id: 'leonardo-phoenix',
    name: 'Leonardo Phoenix',
    provider: 'leonardo',
    modelId: 'phoenix',
    costPer1kTokens: 18.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Leonardo flagship model for cinematic visuals',
    strengths: ['cinematic', 'game-assets', 'photorealistic', 'creative'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 4
  },
  {
    id: 'leonardo-lightning',
    name: 'Leonardo Lightning',
    provider: 'leonardo',
    modelId: 'lightning',
    costPer1kTokens: 5.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Leonardo fastest model for quick iterations',
    strengths: ['ultra-fast', 'game-assets', 'iterative'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 9
  },
  {
    id: 'leonardo-anime',
    name: 'Leonardo Anime',
    provider: 'leonardo',
    modelId: 'anime',
    costPer1kTokens: 12.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Leonardo anime and manga specialized model',
    strengths: ['anime', 'manga', 'illustration', 'character-design'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 10
  },

  // Recraft
  {
    id: 'recraft-v3',
    name: 'Recraft v3',
    provider: 'recraft',
    modelId: 'recraft-v3',
    costPer1kTokens: 20.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Recraft vector-first design model',
    strengths: ['vector', 'brand-design', 'consistent-style', 'logo'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 5
  },
  {
    id: 'recraft-illustration',
    name: 'Recraft Illustration',
    provider: 'recraft',
    modelId: 'recraft-illustration',
    costPer1kTokens: 15.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Recraft illustration and art model',
    strengths: ['illustration', 'artistic', 'editorial'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 11
  },

  // ===== VIDEO GENERATION =====

  // Pika Labs
  {
    id: 'pika-2.1',
    name: 'Pika 2.1',
    provider: 'pika',
    modelId: 'pika-2.1',
    apiUrl: 'https://api.pika.art/v1/generate',
    costPer1kTokens: 250.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Pika Labs advanced video generation — text + image to video',
    strengths: ['text-to-video', 'image-to-video', 'creative-control'],
    category: 'VIDEO_GEN',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'pika-turbo',
    name: 'Pika Turbo',
    provider: 'pika',
    modelId: 'pika-turbo',
    apiUrl: 'https://api.pika.art/v1/generate',
    costPer1kTokens: 120.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Pika fast video generation — lower quality, faster output',
    strengths: ['fast-video', 'quick-preview', 'iterative'],
    category: 'VIDEO_GEN',
    tier: 'BASIC',
    priority: 4
  },

  // Luma AI
  {
    id: 'dream-machine-v2',
    name: 'Dream Machine v2',
    provider: 'luma',
    modelId: 'dream-machine-v2',
    costPer1kTokens: 300.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Luma AI flagship video generation — high quality cinematic',
    strengths: ['cinematic', 'high-quality', 'camera-control', 'looping'],
    category: 'VIDEO_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'luma-photon',
    name: 'Luma Photon',
    provider: 'luma',
    modelId: 'photon-flash',
    costPer1kTokens: 80.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Luma ultra-fast image generation model',
    strengths: ['ultra-fast', 'creative', 'concept-art'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 12
  },

  // Kling (Kuaishou)
  {
    id: 'kling-2.0',
    name: 'Kling 2.0',
    provider: 'kling',
    modelId: 'kling-2.0',
    costPer1kTokens: 280.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Kling 2.0 video generation — strong motion consistency',
    strengths: ['motion-consistency', 'physics-simulation', 'long-form'],
    category: 'VIDEO_GEN',
    tier: 'PREMIUM',
    priority: 3
  },
  {
    id: 'kling-1.6',
    name: 'Kling 1.6',
    provider: 'kling',
    modelId: 'kling-1.6',
    costPer1kTokens: 180.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Kling 1.6 fast video generation',
    strengths: ['fast', 'affordable', 'good-quality'],
    category: 'VIDEO_GEN',
    tier: 'BASIC',
    priority: 5
  },

  // Synthesia (Avatar Video)
  {
    id: 'synthesia-avatar-2.0',
    name: 'Synthesia Avatar 2.0',
    provider: 'synthesia',
    modelId: 'synthesia-avatar-2.0',
    costPer1kTokens: 450.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Synthesia AI avatar video — talking head with script',
    strengths: ['avatar-video', 'talking-head', 'multilingual', 'presentation'],
    languages: ['en', 'de', 'fr', 'es', 'it', 'pt', 'ja', 'zh', 'ko', 'ar'],
    category: 'VIDEO_GEN',
    tier: 'ENTERPRISE',
    priority: 6
  },

  // HeyGen (Avatar Video)
  {
    id: 'heygen-avatar-3.0',
    name: 'HeyGen Avatar 3.0',
    provider: 'heygen',
    modelId: 'heygen-avatar-3.0',
    costPer1kTokens: 400.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'HeyGen avatar video generation — photo-realistic avatars',
    strengths: ['avatar-video', 'photo-realistic', 'custom-avatar', 'lip-sync'],
    category: 'VIDEO_GEN',
    tier: 'ENTERPRISE',
    priority: 7
  },
  {
    id: 'heygen-streaming',
    name: 'HeyGen Streaming',
    provider: 'heygen',
    modelId: 'heygen-streaming',
    costPer1kTokens: 600.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'HeyGen real-time streaming avatar',
    strengths: ['streaming', 'real-time', 'interactive-avatar'],
    category: 'VIDEO_GEN',
    tier: 'ENTERPRISE',
    priority: 8
  },

  // ===== TEXT-TO-SPEECH SPECIALISTS =====

  // Play.ht
  {
    id: 'playht-3.0-mini',
    name: 'PlayHT 3.0 Mini',
    provider: 'playht',
    modelId: 'playht-3.0-mini',
    apiUrl: 'https://api.play.ht/api/v2/tts',
    costPer1kTokens: 8.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'PlayHT efficient TTS — fast generation with natural voices',
    strengths: ['fast-tts', 'natural-voices', 'multilingual'],
    languages: ['en', 'es', 'fr', 'de', 'pt', 'ja', 'ko', 'zh', 'ar', 'hi'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 4
  },
  {
    id: 'playht-3.0',
    name: 'PlayHT 3.0',
    provider: 'playht',
    modelId: 'playht-3.0',
    apiUrl: 'https://api.play.ht/api/v2/tts',
    costPer1kTokens: 15.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'PlayHT flagship TTS with voice cloning',
    strengths: ['voice-cloning', 'emotional', 'studio-quality', 'clone'],
    languages: ['en', 'es', 'fr', 'de', 'pt', 'ja', 'ko', 'zh', 'ar', 'hi'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 5
  },

  // Murf AI
  {
    id: 'murf-studio',
    name: 'Murf Studio',
    provider: 'murf',
    modelId: 'murf-studio',
    costPer1kTokens: 15.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Murf AI studio-quality voiceover TTS',
    strengths: ['voiceover', 'studio-quality', 'narration', 'e-learning'],
    languages: ['en', 'de', 'fr', 'es', 'pt', 'hi', 'ar'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 6
  },

  // Resemble AI
  {
    id: 'resemble-ai',
    name: 'Resemble AI',
    provider: 'resemble',
    modelId: 'resemble-ai',
    costPer1kTokens: 20.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Resemble AI voice cloning and generation',
    strengths: ['voice-cloning', 'deepfake-detection', 'audio-watermarking'],
    languages: ['en', 'fr', 'de', 'es', 'ja', 'ko', 'zh', 'hi'],
    category: 'AUDIO_TTS',
    tier: 'PREMIUM',
    priority: 7
  },

  // Speechify
  {
    id: 'speechify-ai',
    name: 'Speechify AI',
    provider: 'speechify',
    modelId: 'speechify-ai',
    costPer1kTokens: 8.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Speechify TTS with celebrity and natural voices',
    strengths: ['celebrity-voices', 'natural', 'audiobook', 'accessibility'],
    languages: ['en', 'es', 'fr', 'de', 'it', 'pt'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 8
  },

  // ===== MUSIC/AUDIO GENERATION =====

  // Udio
  {
    id: 'udio-v2',
    name: 'Udio v2',
    provider: 'udio',
    modelId: 'udio-v2',
    costPer1kTokens: 150.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Udio flagship AI music generation model',
    strengths: ['music-generation', 'songwriting', 'instrumental', 'high-quality'],
    category: 'IMAGE_GEN', // placeholder — will add AUDIO_GEN category later
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'udio-v2-instrumental',
    name: 'Udio v2 Instrumental',
    provider: 'udio',
    modelId: 'udio-v2-instrumental',
    costPer1kTokens: 120.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Udio v2 for instrumental and background music',
    strengths: ['instrumental', 'background-music', 'soundtrack', 'ambient'],
    category: 'IMAGE_GEN', // placeholder
    tier: 'PREMIUM',
    priority: 2
  },

  // Riffusion
  {
    id: 'riffusion-v1',
    name: 'Riffusion v1',
    provider: 'riffusion',
    modelId: 'riffusion-v1',
    costPer1kTokens: 30.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Riffusion real-time AI music from text prompts',
    strengths: ['real-time', 'music-generation', 'creative', 'experimental'],
    category: 'IMAGE_GEN', // placeholder
    tier: 'BASIC',
    priority: 3
  },

  // ===== PHASE 2: MODELS FOR EXISTING EMPTY PROVIDERS =====

  // Midjourney (previously no models)
  {
    id: 'midjourney-v6.1',
    name: 'Midjourney v6.1',
    provider: 'midjourney',
    modelId: 'midjourney-v6.1',
    costPer1kTokens: 60.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Midjourney latest model — best aesthetic image generation',
    strengths: ['aesthetic', 'artistic', 'highest-quality', 'creative'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'midjourney-v6-turbo',
    name: 'Midjourney v6 Turbo',
    provider: 'midjourney',
    modelId: 'midjourney-v6-turbo',
    costPer1kTokens: 30.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Midjourney fast generation — near-instant results',
    strengths: ['fast', 'aesthetic', 'iterative'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 4
  },
  {
    id: 'niji-6',
    name: 'Niji 6 (Midjourney)',
    provider: 'midjourney',
    modelId: 'niji-6',
    costPer1kTokens: 50.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Midjourney anime/illustration specialized model',
    strengths: ['anime', 'illustration', 'manga', 'character-art'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 3
  },

  // Suno (Music — previously no models)
  {
    id: 'suno-v4',
    name: 'Suno v4',
    provider: 'suno',
    modelId: 'suno-v4',
    costPer1kTokens: 200.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Suno latest AI music generation — full songs with vocals',
    strengths: ['music-generation', 'vocals', 'full-songs', 'multilingual'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },
  {
    id: 'suno-v3.5',
    name: 'Suno v3.5',
    provider: 'suno',
    modelId: 'suno-v3.5',
    costPer1kTokens: 120.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'Suno v3.5 — fast music generation',
    strengths: ['music-generation', 'fast', 'instrumental', 'vocal'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 2
  },

  // AssemblyAI (STT — previously no models)
  {
    id: 'assemblyai-best',
    name: 'AssemblyAI Best',
    provider: 'assemblyai',
    modelId: 'best',
    apiUrl: 'https://api.assemblyai.com/v2/transcript',
    costPer1kTokens: 6.5,
    maxTokens: 50000,
    contextWindow: 50000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'AssemblyAI highest-accuracy speech recognition',
    strengths: ['accurate', 'speaker-diarization', 'entity-detection', 'sentiment'],
    category: 'AUDIO_STT',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'assemblyai-nano',
    name: 'AssemblyAI Nano',
    provider: 'assemblyai',
    modelId: 'nano',
    apiUrl: 'https://api.assemblyai.com/v2/transcript',
    costPer1kTokens: 1.2,
    maxTokens: 50000,
    contextWindow: 50000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'AssemblyAI fast and affordable STT',
    strengths: ['fast', 'affordable', 'streaming'],
    category: 'AUDIO_STT',
    tier: 'BASIC',
    priority: 3
  },

  // Deepgram (STT — previously no models)
  {
    id: 'deepgram-nova-3',
    name: 'Deepgram Nova-3',
    provider: 'deepgram',
    modelId: 'nova-3',
    apiUrl: 'https://api.deepgram.com/v1/listen',
    costPer1kTokens: 5.0,
    maxTokens: 50000,
    contextWindow: 50000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'Deepgram latest STT model — real-time + batch',
    strengths: ['real-time', 'multilingual', 'low-latency', 'custom-vocabulary'],
    languages: ['en', 'es', 'fr', 'de', 'pt', 'ja', 'ko', 'zh', 'hi', 'nl', 'tr'],
    category: 'AUDIO_STT',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'deepgram-nova-2',
    name: 'Deepgram Nova-2',
    provider: 'deepgram',
    modelId: 'nova-2',
    apiUrl: 'https://api.deepgram.com/v1/listen',
    costPer1kTokens: 4.0,
    maxTokens: 50000,
    contextWindow: 50000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'Deepgram proven STT model — high accuracy',
    strengths: ['accurate', 'proven', 'reliable', 'enterprise'],
    category: 'AUDIO_STT',
    tier: 'BASIC',
    priority: 4
  },
  {
    id: 'deepgram-whisper-cloud',
    name: 'Deepgram Whisper Cloud',
    provider: 'deepgram',
    modelId: 'whisper-cloud',
    apiUrl: 'https://api.deepgram.com/v1/listen',
    costPer1kTokens: 3.0,
    maxTokens: 50000,
    contextWindow: 50000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioInput: true,
    description: 'Whisper on Deepgram cloud — managed Whisper inference',
    strengths: ['whisper-compatible', 'managed', 'scalable'],
    category: 'AUDIO_STT',
    tier: 'BASIC',
    priority: 5
  },

  // Runway (Video — previously no models)
  {
    id: 'runway-gen-4',
    name: 'Runway Gen-4',
    provider: 'runway',
    modelId: 'gen-4',
    costPer1kTokens: 400.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Runway latest video generation — high-fidelity output',
    strengths: ['video-generation', 'high-fidelity', 'creative-control', 'editing'],
    category: 'VIDEO_GEN',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'runway-gen-3-alpha-turbo',
    name: 'Runway Gen-3 Alpha Turbo',
    provider: 'runway',
    modelId: 'gen-3-alpha-turbo',
    costPer1kTokens: 150.0,
    maxTokens: 4096,
    contextWindow: 4096,
    supportsChat: false,
    supportsCode: false,
    description: 'Runway Gen-3 fast generation mode',
    strengths: ['fast-video', 'good-quality', 'quick-turnaround'],
    category: 'VIDEO_GEN',
    tier: 'PREMIUM',
    priority: 3
  },

  // Replicate (previously no models)
  {
    id: 'replicate-flux-1.1-pro',
    name: 'Flux 1.1 Pro (Replicate)',
    provider: 'replicate',
    modelId: 'black-forest-labs/flux-1.1-pro',
    apiUrl: 'https://api.replicate.com/v1/predictions',
    costPer1kTokens: 35.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Flux 1.1 Pro via Replicate',
    strengths: ['photorealistic', 'hosted', 'serverless'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 6
  },
  {
    id: 'replicate-sdxl',
    name: 'SDXL (Replicate)',
    provider: 'replicate',
    modelId: 'stability-ai/sdxl',
    apiUrl: 'https://api.replicate.com/v1/predictions',
    costPer1kTokens: 8.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Stable Diffusion XL via Replicate',
    strengths: ['open-source', 'customizable', 'fine-tuned'],
    category: 'IMAGE_GEN',
    tier: 'BASIC',
    priority: 8
  },
  {
    id: 'replicate-llama-3.3-70b',
    name: 'Llama 3.3 70B (Replicate)',
    provider: 'replicate',
    modelId: 'meta/meta-llama-3.3-70b-instruct',
    apiUrl: 'https://api.replicate.com/v1/predictions',
    costPer1kTokens: 0.9,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Llama 3.3 70B on Replicate serverless cloud',
    strengths: ['serverless', 'hosted', 'pay-per-use'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 14
  },

  // Ollama (local — previously no models)
  {
    id: 'ollama-local',
    name: 'Ollama Local',
    provider: 'ollama',
    modelId: 'ollama-auto',
    apiUrl: 'http://localhost:11434/api/generate',
    costPer1kTokens: 0,
    maxTokens: 4096,
    contextWindow: 8192,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Local LLM via Ollama — runs any compatible model locally',
    strengths: ['local', 'private', 'free', 'offline', 'custom-models'],
    category: 'CHAT',
    tier: 'FREE',
    priority: 30
  },

  // OpenRouter (previously no models)
  {
    id: 'openrouter-auto',
    name: 'OpenRouter Auto',
    provider: 'openrouter',
    modelId: 'openrouter/auto',
    apiUrl: 'https://openrouter.ai/api/v1/chat/completions',
    costPer1kTokens: 0.5,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenRouter auto-routing to best available model',
    strengths: ['multi-provider', 'auto-routing', 'cost-optimized', 'fallback'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 20
  },

  // ===== PHASE 3: NEWER MODEL VERSIONS =====

  // OpenAI newer models
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    modelId: 'gpt-4.1',
    costPer1kTokens: 8.0,
    maxTokens: 32768,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    supportsStreaming: true,
    description: 'OpenAI GPT-4.1 — improved instruction following + 1M context',
    strengths: ['instruction-following', 'long-context', 'coding', 'agents'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'openai',
    modelId: 'gpt-4.1-mini',
    costPer1kTokens: 1.5,
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'OpenAI GPT-4.1 Mini — balanced performance and cost',
    strengths: ['balanced', 'cost-effective', '1M-context'],
    category: 'FAST',
    tier: 'PREMIUM',
    priority: 3
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    provider: 'openai',
    modelId: 'gpt-4.1-nano',
    costPer1kTokens: 0.3,
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'OpenAI GPT-4.1 Nano — smallest, fastest, cheapest',
    strengths: ['cheapest', 'fastest', '1M-context', 'lightweight'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 6
  },

  // Anthropic Claude 4 models
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-6-20250501',
    costPer1kTokens: 3.0,
    maxTokens: 16384,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic Claude Sonnet 4.6 — high-intelligence workhorse',
    strengths: ['coding', 'reasoning', 'balanced', 'multimodal'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    modelId: 'claude-opus-4-7-20250501',
    costPer1kTokens: 15.0,
    maxTokens: 32768,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    description: 'Anthropic Claude Opus 4.7 — most powerful for complex tasks',
    strengths: ['best-quality', 'complex-analysis', 'creative', 'agents'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5-20251001',
    costPer1kTokens: 0.8,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    description: 'Anthropic Claude Haiku 4.5 — fastest Claude model',
    strengths: ['fastest', 'cost-effective', 'quick-responses'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 5
  },

  // Google newer models
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    modelId: 'gemini-2.5-pro',
    costPer1kTokens: 10.0,
    maxTokens: 16384,
    contextWindow: 2000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsFiles: true,
    supportsStreaming: true,
    description: 'Google Gemini 2.5 Pro — advanced reasoning + 2M context',
    strengths: ['advanced-reasoning', '2M-context', 'multimodal', 'coding'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 1
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'google',
    modelId: 'gemini-3-flash',
    costPer1kTokens: 0.1,
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'Google Gemini 3 Flash — fast, capable, affordable',
    strengths: ['ultra-fast', 'multimodal', 'affordable', '1M-context'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 2
  },
  {
    id: 'imagen-3',
    name: 'Imagen 3',
    provider: 'google',
    modelId: 'imagen-3',
    costPer1kTokens: 30.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Google Imagen 3 — photorealistic text-to-image',
    strengths: ['photorealistic', 'text-rendering', 'safe'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 2
  },

  // DeepSeek newer model
  {
    id: 'deepseek-r2',
    name: 'DeepSeek R2',
    provider: 'deepseek',
    modelId: 'deepseek-r2',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    costPer1kTokens: 0.8,
    maxTokens: 8192,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'DeepSeek R2 — next-gen reasoning with MoE architecture',
    strengths: ['reasoning', 'math', 'coding', 'cost-effective'],
    category: 'REASONING',
    tier: 'PREMIUM',
    priority: 2
  },

  // xAI Grok-3
  {
    id: 'grok-3',
    name: 'Grok-3',
    provider: 'xai',
    modelId: 'grok-3',
    apiUrl: 'https://api.x.ai/v1/chat/completions',
    costPer1kTokens: 5.0,
    maxTokens: 131072,
    contextWindow: 1000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    supportsStreaming: true,
    description: 'xAI Grok-3 — advanced reasoning + deep search',
    strengths: ['deep-search', 'reasoning', '1M-context', 'multimodal'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 2
  },

  // Groq — newer models
  {
    id: 'groq-llama-4-maverick',
    name: 'Llama 4 Maverick (Groq)',
    provider: 'groq',
    modelId: 'llama-4-maverick',
    costPer1kTokens: 0.8,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    modelSize: '17B',
    description: 'Meta Llama 4 Maverick on Groq — MoE fast inference',
    strengths: ['ultra-fast', 'multimodal', 'efficient', 'reasoning'],
    category: 'FAST',
    tier: 'PREMIUM',
    priority: 8
  },
  {
    id: 'groq-llama-4-scout',
    name: 'Llama 4 Scout (Groq)',
    provider: 'groq',
    modelId: 'llama-4-scout',
    costPer1kTokens: 0.3,
    maxTokens: 8192,
    contextWindow: 10000000,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    modelSize: '17B',
    description: 'Meta Llama 4 Scout on Groq — 10M context window',
    strengths: ['10M-context', 'ultra-fast', 'vision'],
    category: 'VISION',
    tier: 'PREMIUM',
    priority: 9
  },
  {
    id: 'groq-deepseek-r1-llama-70b',
    name: 'DeepSeek R1 Distill 70B (Groq)',
    provider: 'groq',
    modelId: 'deepseek-r1-distill-llama-70b',
    costPer1kTokens: 0.69,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    description: 'DeepSeek R1 reasoning distilled on Llama 70B',
    strengths: ['fast-reasoning', 'chain-of-thought', 'math'],
    category: 'REASONING',
    tier: 'BASIC',
    priority: 10
  },

  // Together AI — newer models
  {
    id: 'together-llama-4-maverick',
    name: 'Llama 4 Maverick (Together)',
    provider: 'together',
    modelId: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.8,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsChat: true,
    supportsCode: true,
    supportsVision: true,
    modelSize: '17B',
    description: 'Llama 4 Maverick MoE model on Together',
    strengths: ['multimodal', 'MoE', 'efficient', 'vision'],
    category: 'MULTIMODAL',
    tier: 'PREMIUM',
    priority: 11
  },
  {
    id: 'together-deepseek-v3',
    name: 'DeepSeek V3 (Together)',
    provider: 'together',
    modelId: 'deepseek-ai/DeepSeek-V3',
    apiUrl: 'https://api.together.xyz/v1/chat/completions',
    costPer1kTokens: 0.9,
    maxTokens: 8192,
    contextWindow: 64000,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'DeepSeek V3 via Together — hosted access',
    strengths: ['cost-effective', 'reasoning', 'hosted'],
    category: 'CHAT',
    tier: 'BASIC',
    priority: 13
  },

  // Mistral newer model
  {
    id: 'mistral-small-latest',
    name: 'Mistral Small',
    provider: 'mistral',
    modelId: 'mistral-small-latest',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    costPer1kTokens: 0.1,
    maxTokens: 16384,
    contextWindow: 32768,
    supportsChat: true,
    supportsCode: true,
    supportsStreaming: true,
    description: 'Mistral Small — cheapest API-accessible Mistral model',
    strengths: ['affordable', 'fast', 'multilingual', 'simple-tasks'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 16
  },

  // Stability AI newer models
  {
    id: 'stable-diffusion-3.5-large',
    name: 'Stable Diffusion 3.5 Large',
    provider: 'stability',
    modelId: 'stable-diffusion-3.5-large',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-diffusion-3.5-large/text-to-image',
    costPer1kTokens: 10.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Stability flagship model — 8B params, MMDiT architecture',
    strengths: ['photorealistic', 'versatile', 'prompt-adherence', 'diverse'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 2
  },
  {
    id: 'stable-image-ultra',
    name: 'Stable Image Ultra',
    provider: 'stability',
    modelId: 'stable-image-ultra',
    apiUrl: 'https://api.stability.ai/v1/generation/stable-image-ultra/text-to-image',
    costPer1kTokens: 20.0,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsImageGen: true,
    description: 'Stability highest-quality image generation API',
    strengths: ['ultra-quality', 'production', 'professional'],
    category: 'IMAGE_GEN',
    tier: 'PREMIUM',
    priority: 1
  },

  // Perplexity newer model
  {
    id: 'sonar-reasoning-pro',
    name: 'Sonar Reasoning Pro',
    provider: 'perplexity',
    modelId: 'sonar-reasoning-pro',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    costPer1kTokens: 8.0,
    maxTokens: 16384,
    contextWindow: 200000,
    supportsChat: true,
    supportsCode: true,
    description: 'Perplexity advanced reasoning with deep research',
    strengths: ['deep-research', 'reasoning', 'web-search', 'citations'],
    category: 'REASONING',
    tier: 'ENTERPRISE',
    priority: 4
  },

  // ElevenLabs newer models
  {
    id: 'eleven-flash-v2-5',
    name: 'ElevenLabs Flash v2.5',
    provider: 'elevenlabs',
    modelId: 'eleven_flash_v2_5',
    apiUrl: 'https://api.elevenlabs.io/v1/text-to-speech',
    costPer1kTokens: 5.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'ElevenLabs ultra-fast low-latency TTS',
    strengths: ['ultra-fast', 'low-latency', 'streaming', 'real-time'],
    languages: ['en', 'de', 'pl', 'es', 'it', 'fr', 'pt', 'hi'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 6
  },
  {
    id: 'eleven-turbo-v2-5',
    name: 'ElevenLabs Turbo v2.5',
    provider: 'elevenlabs',
    modelId: 'eleven_turbo_v2_5',
    apiUrl: 'https://api.elevenlabs.io/v1/text-to-speech',
    costPer1kTokens: 8.0,
    maxTokens: 5000,
    contextWindow: 5000,
    supportsChat: false,
    supportsCode: false,
    supportsAudioOutput: true,
    description: 'ElevenLabs fast TTS — good balance of speed and quality',
    strengths: ['fast', 'quality', 'multilingual', 'voice-cloning'],
    languages: ['en', 'de', 'pl', 'es', 'it', 'fr', 'pt', 'hi', 'ar', 'zh', 'ja', 'ko'],
    category: 'AUDIO_TTS',
    tier: 'BASIC',
    priority: 7
  },

  // Cohere newer models
  {
    id: 'command-r7b',
    name: 'Command R7B',
    provider: 'cohere',
    modelId: 'command-r7b-12-2024',
    apiUrl: 'https://api.cohere.ai/v1/chat',
    costPer1kTokens: 0.1,
    maxTokens: 4096,
    contextWindow: 128000,
    supportsChat: true,
    supportsCode: true,
    modelSize: '7B',
    description: 'Cohere smallest RAG model — fast + affordable',
    strengths: ['RAG', 'fast', 'affordable', 'lightweight'],
    category: 'FAST',
    tier: 'BASIC',
    priority: 14
  },
  {
    id: 'embed-v4',
    name: 'Cohere Embed v4',
    provider: 'cohere',
    modelId: 'embed-v4.0',
    apiUrl: 'https://api.cohere.ai/v1/embed',
    costPer1kTokens: 0.1,
    maxTokens: 2048,
    contextWindow: 2048,
    supportsChat: false,
    supportsCode: false,
    supportsEmbeddings: true,
    description: 'Cohere latest embedding model — 4096 dimensions',
    strengths: ['semantic-search', '4096-dimensions', 'multilingual'],
    category: 'EMBEDDING',
    tier: 'BASIC',
    priority: 3
  },
];

// Validate and create the final models array with defaults
export const ALL_MODELS: Model[] = RAW_MODELS.map(model =>
  ModelSchema.parse(model)
);

// Environment variable mappings for API keys
export const API_KEY_MAPPINGS = {
  // Major LLM providers
  openai: 'OPENAI_API_KEY',
  anthropic: 'ANTHROPIC_API_KEY',
  google: 'GOOGLE_API_KEY',
  cohere: 'COHERE_API_KEY',
  mistral: 'MISTRAL_API_KEY',
  meta: 'META_API_KEY',
  huggingface: 'HUGGINGFACE_API_KEY',
  ollama: 'OLLAMA_API_KEY',
  together: 'TOGETHER_API_KEY',
  perplexity: 'PERPLEXITY_API_KEY',
  groq: 'GROQ_API_KEY',
  replicate: 'REPLICATE_API_KEY',
  stability: 'STABILITY_API_KEY',
  midjourney: 'MIDJOURNEY_API_KEY',
  runpod: 'RUNPOD_API_KEY',
  // New LLM providers (2024)
  deepseek: 'DEEPSEEK_API_KEY',
  xai: 'XAI_API_KEY',
  fireworks: 'FIREWORKS_API_KEY',
  openrouter: 'OPENROUTER_API_KEY',
  anyscale: 'ANYSCALE_API_KEY',
  nvidia: 'NVIDIA_API_KEY',
  qwen: 'QWEN_API_KEY',
  // Specialized audio/media providers
  elevenlabs: 'ELEVENLABS_API_KEY',
  assemblyai: 'ASSEMBLYAI_API_KEY',
  deepgram: 'DEEPGRAM_API_KEY',
  suno: 'SUNO_API_KEY',
  runway: 'RUNWAY_API_KEY',
  // Fast LLM inference (2025)
  cerebras: 'CEREBRAS_API_KEY',
  sambanova: 'SAMBANOVA_API_KEY',
  // Enterprise LLM
  ai21: 'AI21_API_KEY',
  // Embeddings specialists
  voyage: 'VOYAGE_API_KEY',
  jina: 'JINA_API_KEY',
  // Image generation (2025)
  blackforest: 'BLACKFOREST_API_KEY',
  ideogram: 'IDEOGRAM_API_KEY',
  leonardo: 'LEONARDO_API_KEY',
  recraft: 'RECRAFT_API_KEY',
  // Video generation
  pika: 'PIKA_API_KEY',
  luma: 'LUMA_API_KEY',
  kling: 'KLING_API_KEY',
  synthesia: 'SYNTHESIA_API_KEY',
  heygen: 'HEYGEN_API_KEY',
  // TTS specialists
  playht: 'PLAYHT_API_KEY',
  murf: 'MURF_API_KEY',
  resemble: 'RESEMBLE_API_KEY',
  speechify: 'SPEECHIFY_API_KEY',
  // Music generation
  udio: 'UDIO_API_KEY',
  riffusion: 'RIFFUSION_API_KEY'
} as const;

// Model categories for routing
export const MODEL_CATEGORIES = {
  // Text-based categories
  CHAT: 'Conversational AI and general queries',
  CODE: 'Code generation and programming assistance',
  REASONING: 'Complex reasoning and analysis',
  CREATIVE: 'Creative writing and content generation',
  FAST: 'Quick responses and real-time applications',
  VISION: 'Image and visual content analysis',
  MULTIMODAL: 'Multi-format content processing',

  // Generation categories
  IMAGE_GEN: 'AI image generation (DALL-E, Stable Diffusion, Midjourney)',
  VIDEO_GEN: 'AI video generation and editing',

  // Audio categories
  AUDIO_STT: 'Speech-to-text transcription (Whisper)',
  AUDIO_TTS: 'Text-to-speech synthesis',

  // Utility categories
  EMBEDDING: 'Text embeddings for semantic search and RAG'
} as const;

export type ModelProvider = keyof typeof API_KEY_MAPPINGS;
export type ModelCategory = keyof typeof MODEL_CATEGORIES;